### ISSUE TITLE
建议恢复合成材料足够时的合成步骤

### ISSUE THREAD

**Issue by Yanstory** [arkntools/arknights-toolbox#10]
知道自己材料够，但是还是需要知道合多少个的，万一手滑了呢（捂脸）

**Comment by Tsuk1ko** [comment]
有点没明白意思，能不能简单描述下目前情况和你想要的结果🤔

**Comment by Yanstory** [comment]
之前的版本在精英材料足够的时候会显示中途需要的合成步骤（如最终需求蓝土，但是只有绿土，会显示「需要合成 蓝土xxx」），现在直接就是「根本不需要计算了」，需要自己算一下合成的时候合多少个

**Comment by Tsuk1ko** [comment]
你指的是哪里的显示，目前不管是页面上直接可见的还是刷图计算都有标明需要合成的数量

![image](https://user-images.githubusercontent.com/24877906/68574643-54f9e680-04a5-11ea-8e9c-07bd26f99e49.png)

**Comment by Yanstory** [comment]
原来现在直接用这个的吗😂之前一直都是点「我该刷什么图」来看的，但是现在看不了了，后来有了简洁模式我也把简洁模式打开了，没注意这里（捂脸），这样的话谢谢dalao了
![IMG_20191111_171404](https://user-images.githubusercontent.com/5153875/68575348-d1d99000-04a6-11ea-9c20-a5384d35b027.jpg)

**Comment by Tsuk1ko** [comment]
啊是这样的，这个计算刷图是当你仍有需要获取的素材的时候才需要计算，告诉你刷哪些图，如果你已经满足需求了自然就不需要计算刷图了（

**Comment by Yanstory** [comment]
长期使用下来感觉在todo过多的时候实在不方便计算合成状态，建议还是恢复，即使不需要刷图也列出合成的具体步骤

**Comment by Tsuk1ko** [comment]
😂可是那个只是把要合成的数量列出来而已啊，也没有具体合成先后步骤，和直接看小括号数字是一样的

而且在普通模式下直接按稀有度从低到高一个个来合成就可以了，我还列了心情消耗可以让你更好的分配副产物加成干员

**Comment by Yanstory** [comment]
举个例子，我现在有四个todo任务，但是我现在只想优先完成任务A的材料准备
而todo只告诉了我A的金材料和紫材料的合成数量，并不能告诉我合成路线
虽然我可以通过关闭【简洁模式】通过鼠标指向来查看合成路线，但始终不如完整的合成路线图来的快。

**Comment by Tsuk1ko** [comment]
这个就属于新功能需求了，“恢复”并不能解决这个问题

我目前的想法是给 todo 每一条加一个点击高亮合成路径材料的按钮

**Comment by Yanstory** [comment]
可以，那我这边就关闭这个issue了

**Comment by Tsuk1ko** [comment]
高亮功能已经实装了
