### ISSUE TITLE
精英材料云端备份成功但提示文字显示“恢复失败”

### ISSUE THREAD

**Issue by SilverashMeiyuu** [arkntools/arknights-toolbox#103]
测试了一下，虽然备份后提示文字是“恢复失败”，但是能正常备份，只是提示文字错误。

**Comment by Tsuk1ko** [comment]
提示文字确实错了，但也确实备份失败了，不知为何 jsonbox.io 限制跨域了，可能和它要停止服务了有关，我还得找个新的免费 json 储存
