### ISSUE TITLE
能否加入主线进度的选择的功能

### ISSUE THREAD

**Issue by Bruce-Ch** [arkntools/arknights-toolbox#104]
对于刷图设计，很多时候会建议去第七章或者第八章，但对于新手玩家而言这些章节可能不适合刷图（用了助战等），是否可能添加一个交互用于设定主线推图进度

**Comment by Bruce-Ch** [comment]
（我可能可以帮助完成这一部分的代码

**Comment by Tsuk1ko** [comment]
已经有这一计划了，参见 #98
