### ISSUE TITLE
请问能否将工具箱移植到cq-picsearcher-bot上

### ISSUE THREAD

**Issue by jx9468** [arkntools/arknights-toolbox#105]
能不能将工具箱像公招查询一样移植到cq-picsearcher-bot上ฅ۶•ﻌ•♡，方便使用，工程量太大的话那抱歉打扰了+_+

**Comment by Tsuk1ko** [comment]
问题是，除了公招查询，你觉得还有什么功能是可以通过机器人使用并且不损失易用性的呢

**Comment by jx9468** [comment]
> 问题是，除了公招查询，你觉得还有什么功能是可以通过机器人使用并且不损失易用性的呢
类似这种干员升级材料专精材料之类的，还有就是一些材料关卡之类的可以做成推送丫ฅ۶•ﻌ•♡
![T7{26GZ_(7VG~0Y3BDLXO%1](https://user-images.githubusercontent.com/78193384/110746900-7ecd4400-8278-11eb-9fea-1023a3993a0b.jpg)

**Comment by Tsuk1ko** [comment]
按我自己平时养成的习惯来说，光看意义真的不太大……不如打开工具箱识别下材料导个预设看看自己实际缺多少东西，干员信息的话直接打开 PRTS wiki 去看也更方便

材料关卡感觉没有什么值得推送的，[aog.wiki](https://aog.wiki) 已经足够详细，需要的时候点进去看看就行

**Comment by jx9468** [comment]
> 按我自己平时养成的习惯来说，光看意义真的不太大……不如打开工具箱识别下材料导个预设看看自己实际缺多少东西，干员信息的话直接打开 PRTS wiki 去看也更方便
> 
> 材料关卡感觉没有什么值得推送的，[aog.wiki](https://aog.wiki) 已经足够详细，需要的时候点进去看看就行

我觉得机器人的话更为方便简洁，我想象的是hoshinobot那种类型专项一个游戏，也更有趣味性，方便在群里讨论⊙ω⊙

**Comment by Tsuk1ko** [comment]
这样的话就不应该添加到 cq-picsearcher-bot 上了，而是应该开发一个方舟专用的机器人

我没有做这个的打算，因为我懒，而且自己没有这种需求
![image](https://user-images.githubusercontent.com/24877906/110750095-f309e680-827c-11eb-9aeb-0b176e693796.png)

**Comment by jx9468** [comment]
> 这样的话就不应该添加到 cq-picsearcher-bot 上了，而是应该开发一个方舟专用的机器人
> 
> 我没有做这个的打算，因为我懒，而且自己没有这种需求
> ![image](https://user-images.githubusercontent.com/24877906/110750095-f309e680-827c-11eb-9aeb-0b176e693796.png)

这不是没人做方舟的bot吗，看你有做方舟的工具箱就想问问你们做吗😭😭

**Comment by Tsuk1ko** [comment]
🤔可能是因为性价比不高吧，个人感觉方舟对 bot 的依赖程度确实没 PCR 这么大，PCR 是因为公会战出刀管理这个需求点刚好可以和 bot 结合起来，它确实极大的方便了玩家，几乎成了一个必备功能，所以在此之上也很容易顺理成章扩展出其他功能

方舟并没有什么核心功能是和 bot 契合度很高的，自然就没什么人做，顶多只是公招查询这类功能我觉得还挺方便的，所以它以附加功能的形式出现在 cq-picsearcher-bot 中

其它可以做进去的功能比如方舟B博推送、活动结束提醒等等，其实我自己是有写的，但只是自用而已，因为都是些非常小的功能，直接扔 serverless 上就完了，开源出来还有额外的维护成本

总之我没有非常强烈的需求，所以我并不考虑单独做个 bot，毕竟维护开源项目也是要付出很多精力的

要不你可以试试学习编程成为开发方舟 bot 的第一人，指不定以后我就去用你的 bot 了😂

**Comment by jx9468** [comment]
> 🤔可能是因为性价比不高吧，个人感觉方舟对 bot 的依赖程度确实没 PCR 这么大，PCR 是因为公会战出刀管理这个需求点刚好可以和 bot 结合起来，它确实极大的方便了玩家，几乎成了一个必备功能，所以在此之上也很容易顺理成章扩展出其他功能
> 
> 方舟并没有什么核心功能是和 bot 契合度很高的，自然就没什么人做，顶多只是公招查询这类功能我觉得还挺方便的，所以它以附加功能的形式出现在 cq-picsearcher-bot 中
> 
> 其它可以做进去的功能比如方舟B博推送、活动结束提醒等等，其实我自己是有写的，但只是自用而已，因为都是些非常小的功能，直接扔 serverless 上就完了，开源出来还有额外的维护成本
> 
> 总之我没有非常强烈的需求，所以我并不考虑单独做个 bot，毕竟维护开源项目也是要付出很多精力的
> 
> 要不你可以试试学习编程成为开发方舟 bot 的第一人，指不定以后我就去用你的 bot 了😂

我就一个做等秃头的特效师，没那技术力😂😂等什么时候想做特效工程师了再看了🤣
