### ISSUE TITLE
基建技能筛选中空弦不在任何分类

### ISSUE THREAD

**Issue by happywilson1223** [arkntools/arknights-toolbox#107]
基建技能筛选里
空弦不在 [订单效率] [订单上限] [高品质] 任何一分类中
只有选择贸易站设施才会显示在最底部
正常应分类于 [订单效率] 中
宿舍皆满等情况下自身可提供+40%订单获取效率

**Comment by Tsuk1ko** [comment]
修复了，空弦将会在订单效率分类中

为了节省维护精力，工具箱所有数据都是从解包中自动更新的，按照“可以最大程度满足后续版本”的思路来设计，因此对于这些数据的解析都是通用流程，不会为某些干员专门写入额外的数据，如果技能描述中没有“最多提供xx%效率”这类字眼，就无法得知最高效率，也没办法自动将其算出，所以排序问题无法解决，请谅解

今后会改进，把没有写明最高效率但具有特殊效果的技能单独分为一类以防止不合理的排序
