### ISSUE TITLE
为什么仓库识别成功率很低呢。

### ISSUE THREAD

**Issue by whyjxz14** [arkntools/arknights-toolbox#109]
![image](https://user-images.githubusercontent.com/6323818/113094978-3ffe2e80-9225-11eb-9776-b999a2b1377a.png)
像这个完全都不成功
![image](https://user-images.githubusercontent.com/6323818/113095017-4e4c4a80-9225-11eb-81a9-8bcad93b6a9d.png)
59一定会识别为52.试多少次都是

https://gachasalt.github.io/ArkToolDemo/#/image
https://github.com/GachaSalt/ArkToolDemo
它这个仓库识别成功率就非常高，几乎100%

**Comment by Tsuk1ko** [comment]
改进了

因为我菜呗。

它这个仓库识别只放了成品，又不是源码，我又没法借鉴

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/113117711-4f8b7080-9241-11eb-843f-2dd5830e82d3.png)
你看看这是什么……
