### ISSUE TITLE
基建技能显示&筛选问题

### ISSUE THREAD

**Issue by ngc7331** [arkntools/arknights-toolbox#113]
![image](https://user-images.githubusercontent.com/22112348/114813389-98682b00-9de4-11eb-8bb2-57d7e2176fe3.png)
![image](https://user-images.githubusercontent.com/22112348/114814197-44f6dc80-9de6-11eb-97b8-f847511c7590.png)
如图1~2，看起来像是一小时前的commit向src/data/building.json引入了多余的字符导致的

![image](https://user-images.githubusercontent.com/22112348/114814568-057cc000-9de7-11eb-91b0-2c4c7b0f38b4.png)
此外还有蓝色字体范围错误（同图1）和筛选错误（图3，不是截图没截全而是筛选结果为空），已确认上一个版本（4天前）无此问题

**Comment by ngc7331** [comment]
[嗯应该是鹰角改动文案时加了一堆标签导致的](https://github.com/Kengxxiao/ArknightsGameData/commit/7474cdb4d1271bbee45fcead4e005d465ea48e44)
![image](https://user-images.githubusercontent.com/22112348/114815605-1e867080-9de9-11eb-9daa-24fd799b9a54.png)

**Comment by Tsuk1ko** [comment]
是的，在修了（

**Comment by Tsuk1ko** [comment]
修了，后续还打算加入术语说明，晚上搞

![image](https://user-images.githubusercontent.com/24877906/114824637-c6a33600-9df7-11eb-9757-d88c734e6744.png)
