### ISSUE TITLE
公招计算增强：三星及以上公招专属干员高亮

### ISSUE THREAD

**Issue by Yanstory** [arkntools/arknights-toolbox#114]
![image](https://user-images.githubusercontent.com/5153875/115137047-429ab980-a056-11eb-8079-404f4b6642ae.png)
目前的高亮还仅限于对不可公招干员的高亮，建议加一个三星及以上公招专属干员的高亮

一个参考
![image](https://user-images.githubusercontent.com/5153875/115137200-4713a200-a057-11eb-90e4-acf786b4f0b3.png)

**Comment by Tsuk1ko** [comment]
目前唯一的问题是无法从[解包](https://github.com/Kengxxiao/ArknightsGameData/blob/master/zh_CN/gamedata/excel/character_table.json)中确定某个干员是否“仅能通过招募获得”或“不能通过寻访获得”

目前我找到的能判断干员来源的字段只有 `itemObtainApproach`，看起来该字段只是被用于在游戏中展示干员来源，并非确定的枚举值，并且“招募”和“寻访”算为同一类

清流的话是限时礼包还好，像火神和因陀罗就无法区分

![image](https://user-images.githubusercontent.com/24877906/115138543-75957b00-a05f-11eb-9dc9-d98f8410a0f8.png)

**Comment by ngc7331** [comment]
也许可以从公招说明[gacha_table.json](https://github.com/Kengxxiao/ArknightsGameData/blob/master/zh_CN/gamedata/excel/gacha_table.json)的recruitDetail值（现为2089行）里面找所有带<@rc.eml>标签的角色？

**Comment by Tsuk1ko** [comment]
@ngc7331 工具箱现有的更新逻辑也是从 `recruitDetail` 中获取公开招募干员列表，但这里只能得到“**可以**从公开招募中获得”的干员，而现在需要的是“**仅能**通过公开招募获得”的干员

**Comment by ngc7331** [comment]
> @ngc7331 工具箱现有的更新逻辑也是从 `recruitDetail` 中获取公开招募干员列表，但这里只能得到“**可以**从公开招募中获得”的干员，而现在需要的是“**仅能**通过公开招募获得”的干员

我看到现在是直接`.replace(/<.+?>(.+?)<\/>/g, '$1')`去除html标签，但是`recruitDetail`里面有绿色高亮`<@rc.eml>`标签的应该都是“**仅能**通过公开招募获得”的干员，我的意思是能否通过匹配这个标签来确定角色是否公招限定

> ......<@rc.eml>绿色高亮的不可寻访干员，可以在此招募</>\n\n★\\n<@rc.eml>Lancet-2</>......
![image](https://user-images.githubusercontent.com/22112348/115140820-d460f180-a06b-11eb-9333-4e9e58c67470.png)

**Comment by Tsuk1ko** [comment]
@ngc7331 懂了，确实可行
