### ISSUE TITLE
精英材料内所有“仍需”始终为0

### ISSUE THREAD

**Issue by FlandiaYingman** [arkntools/arknights-toolbox#116]
![Screenshot_2021-04-28-17-05-58-438_com android chrome](https://user-images.githubusercontent.com/9929037/116378113-645d2300-a844-11eb-8730-11c11d09b82b.jpg)
如图。材料均从仓库截图中导入；浏览器为Chrome。

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/116378655-ed745a00-a844-11eb-97c3-ac68bda15273.png)

**Comment by FlandiaYingman** [comment]
@Tsuk1ko 抱歉，我先前认为以为括号外的数字是包含能合成的数量的。

**Comment by Tsuk1ko** [comment]
没事😊
