### ISSUE TITLE
关于公开招募计算的OCR功能

### ISSUE THREAD

**Issue by Elypha** [arkntools/arknights-toolbox#118]
最近用了一周左右公开招募工具，偶尔会遇到识别不完整的情况，比如5个tag只认出了4个这样。有可能是因为我模拟器窗口开的不大，截图分辨率小（大概是一张500宽度的图，只包含tag部分）。

例图
![image](https://user-images.githubusercontent.com/30290883/117335773-7a1eb800-aed6-11eb-9aab-12085ca84324.png)

我在想，针对通过OCR方式进行的导入，或许可以对识别结果加一步额外的数量检测（是否等于5），并在不等于5的情况下给出提示。

另外不知道开发组是否愿意支持百度提供的OCR服务（排除对公司的评价……在自己写的一些小脚本里用过，感觉准确度还行……），各种类有500~50000的每日免费额度。

**Comment by Tsuk1ko** [comment]
不足5时提示可以有

本项目是无后端的，因此如果要使用百度OCR就必须让用户自行开通并设置AK和SK，会有点繁琐，当然作为一个后备选择也不是不行

**Comment by Elypha** [comment]
十分感谢！
主要是想了一下，tag不准手动修一下可能也不花很多时间……比起来代码上的工作量可能就显得有点多……当然还是取决于开发组）

**Comment by Tsuk1ko** [comment]
试了下，百度OCR和腾讯OCR这类的 API 都不允许跨域调用，不能直接在网页上用，那凉了

**Comment by Elypha** [comment]
原来如此（悲）
