### ISSUE TITLE
Idea: 支持俄语名字的拉丁字母转写形式

### ISSUE THREAD

**Issue by SaltfishAmi** [arkntools/arknights-toolbox#119]
那天在工具箱上看熊熊们的精二材料……
凛冬 Зима = Zima，出来了。
早露 Роса = Rosa，出来了。
古米 Гум = Gum，出来了。
真理 Истина = Istina……嗯？为什么没有？
哦，isuchina出来了……合着前面三个也是日文罗马音啊？
幼小的心灵受到了震撼。
如果能支持西里尔字母的拉丁转写形式，让istina直接能出就更好了……

**Comment by Tsuk1ko** [comment]
可，晚点看看好不好搞
