### ISSUE TITLE
幹員升級計算能否進行多隻計算

### ISSUE THREAD

**Issue by KowenK** [arkntools/arknights-toolbox#120]
比說可以一次計算兩隻或以上不同等級的角色升級所需的資源或材料，然後把總共需要的減掉手上有的資源(跟目前顯示的一樣)

**Comment by Tsuk1ko** [comment]
可以，会加上这个功能

**Comment by Tsuk1ko** [comment]
现在你可以通过这个按钮添加多个计算
![image](https://user-images.githubusercontent.com/24877906/127737181-adc8d2f2-77e0-4918-8a69-afb8b4ba7ae6.png)
