### ISSUE TITLE
公开招募计算会列出不可能招募的五星、六星

### ISSUE THREAD

**Issue by Yatogamikaka** [arkntools/arknights-toolbox#121]
用了一周，才发现之前的可能出现的组合角色都是不能通过公开招募获得的，有点迷惑（刚入坑的萌新），希望可以改进一下

**Comment by Tsuk1ko** [comment]
如果开了这个选项就会列出非公招干员，关掉即可

![image](https://user-images.githubusercontent.com/24877906/119264812-3a1a3d80-bc17-11eb-93b5-0a475fb51cad.png)
