### ISSUE TITLE
公招能否在保底词条组合中进行筛选？

### ISSUE THREAD

**Issue by Endless-dream** [arkntools/arknights-toolbox#123]
除特种和快活，保底词条中至少会有一个两字词条，所以每次出现像是“生存”之类的词条，我都会来查看保底组合

但是在所有保底组合中寻找比较麻烦，希望可以直接在保底列表中筛选

把“查看保底词条组合”改成“只出现保底词条组合”，类似这样

辛苦啦！祝好

**Comment by Endless-dream** [comment]
保底词条中二字词条的出现次数：

控场1  爆发1  治疗5  支援4  输出8  生存5  群攻2  防护4  减速10  削弱6  位移5  召唤1  

在笔记本上除了减速都是能全部显示出来的，一目了然

再次希望可以直接在保底词条中进行筛选……

**Comment by Tsuk1ko** [comment]
实装了

![image](https://user-images.githubusercontent.com/24877906/127737238-9486a6ff-af1e-4859-99d7-8a20dc45ef69.png)

**Comment by Endless-dream** [comment]
感谢大大


　　　　　_∧＿∧_
　　　　 ((∀｀/ 　)
　　　 /⌒　　  ／
　　 /(__ノ＼_ノ
　　(_ノ |||
好棒啊~~赞~~~　
　∧＿∧　∧＿∧
(( ・∀・ ))・∀・) )
`＼　　 ∧ 　　ノ
　/　　｜/　　｜
（＿ノ＿)_ノL＿)
 



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 晚上6:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [arkntools/arknights-toolbox] 公招能否在保底词条组合中进行筛选？ (#123)




 
实装了
