### ISSUE TITLE
增加常驻活动掉落

### ISSUE THREAD

**Issue by Zengqizq** [arkntools/arknights-toolbox#126]
现在有很多常驻的别传和插曲，能否将他们的掉落加入素材规划计算让素材获取更高效

**Comment by Tsuk1ko** [comment]
可以加，不过实际上并不会提升素材效率

常驻别传和插曲的素材效率是远低于活动时的效率的，比主线效率要低

**Comment by Zengqizq** [comment]
这样啊，因为今天偶然用企鹅物流的规划对比了一下，他给我推荐了几个常驻关像sv9 off4

**Comment by Tsuk1ko** [comment]
> 这样啊，因为今天偶然用企鹅物流的规划对比了一下，他给我推荐了几个常驻关像sv9 off4

确实有些关卡效率会高于主线

现在这个功能已经实装了
