### ISSUE TITLE
建议增加插曲·别传的规划

### ISSUE THREAD

**Issue by yd278** [arkntools/arknights-toolbox#127]
现在企鹅物流上已经有足够多的插曲和别传的样本，有些数据也确实优于主线（如GT-5别传的扭转醇单件期望理智甚至优于VI-7）。且在企鹅物流内置的规划器上也会将插曲别传的关卡规划在内。希望能在工具箱里也用到这样的功能

**Comment by yd278** [comment]
啊我看错了，我以为上个issue都几个月前了只是忘了close Orz
和https://github.com/arkntools/arknights-toolbox/issues/126 重复了，酌情close吧

**Comment by Tsuk1ko** [comment]
> 现在企鹅物流上已经有足够多的插曲和别传的样本，有些数据也确实优于主线（如GT-5别传的扭转醇单件期望理智甚至优于VI-7）。且在企鹅物流内置的规划器上也会将插曲别传的关卡规划在内。希望能在工具箱里也用到这样的功能

确实
