### ISSUE TITLE
刷图规划中仍存在已结束的活动？

### ISSUE THREAD

**Issue by Killuahiei** [arkntools/arknights-toolbox#129]
21.7.21查看刷图规划时提示我应该刷的图包括WD-8，右侧也有提示是遗尘漫步・插曲的活动图，但是这个活动已经结束了。我记得之前是活动结束就不显示了？
而且这个遗尘漫步也不是刚结束的活动，是21年4月的活动，所以觉得有点奇怪。

**Comment by Tsuk1ko** [comment]
这是插曲和别传，如果你还没解锁可以在刷图规划设置里把对应的章节取消勾选

![image](https://user-images.githubusercontent.com/24877906/126416318-2f6c3452-acef-408b-a108-aac011a02e52.png)

**Comment by Killuahiei** [comment]
是这样，这个插曲我从没注意过可以刷材料，谢谢告知！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 上午9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [arkntools/arknights-toolbox] 刷图规划中仍存在已结束的活动？ (#129)





 
这是插曲和别传，如果你还没解锁可以在刷图规划设置里把对应的章节取消勾选
