### ISSUE TITLE
基建技能筛选里【会客室】和【(1) 莱茵生命】里没有【山】

### ISSUE THREAD

**Issue by bearpool** [arkntools/arknights-toolbox#130]
![微信截图_20210725121636](https://user-images.githubusercontent.com/6859847/126887560-3d4b984b-1ed5-4905-a8da-33436f46e66f.png)
如图是【(1) 莱茵生命】的，设施的【会客室】里同样找不到【山】

**Comment by Tsuk1ko** [comment]
会客室是有的，莱茵生命没有
