### ISSUE TITLE
合并“至少需要”和“预计消耗”

### ISSUE THREAD

**Issue by Z7012** [arkntools/arknights-toolbox#137]
当已有小于需求时，已有会自动变成需求的数据
![ScreenShot00305](https://user-images.githubusercontent.com/90760702/133409671-ce10d2da-0167-4c93-9e20-003d08ed195e.png)
提个小建议，可以把仍需龙门币和仍需经验书放在一起。

**Comment by Tsuk1ko** [comment]
预计消耗的这个“已有”是 左侧你填写的“已有” + 刷本获得的狗粮

例如高级狗粮 66 = 27 + 39

**Comment by Tsuk1ko** [comment]
> 提个小建议，可以把仍需龙门币和仍需经验书放在一起。

确实可以，可以把上下两个模块合并了

**Comment by Z7012** [comment]
> 预计消耗的这个“已有”是 左侧你填写的“已有” + 刷本获得的狗粮
> 
> 例如高级狗粮 66 = 27 + 39

好的，之后我也理解了，想删掉issue发现没法删......（才注册）
感谢！

**Comment by Tsuk1ko** [comment]
没事，有改进点，先保持 open
