### ISSUE TITLE
最优基建换班策略

### ISSUE THREAD

**Issue by tkkcc** [arkntools/arknights-toolbox#140]
最优基建换班策略目前还没发现有人做，可以帮助对基建换班研究不深的玩家提高收益。

流程可以这样：用户上传多张干员列表截图和基建截图，网页分析出干员与精英化等级，由此推断所有基建技能，结合基建各类站数量与等级计算最高产出的换班策略。

难点是求解算法。

大佬觉得怎么样。

**Comment by Tsuk1ko** [comment]
不考虑……

玩家是来玩游戏的不是来上班的，没必要，真的

平时就一天上两次，周末睡个懒觉还会红一片，真的有人会定闹钟去换班吗😂

**Comment by Tsuk1ko** [comment]
对基建不熟的话，可能看看 nga 或者B站找教学更好
