### ISSUE TITLE
公开招募：治疗+支援并不能锁5星，还有清流

### ISSUE THREAD

**Issue by Ryanrrt** [arkntools/arknights-toolbox#142]
白激动了QAQ

**Comment by Tsuk1ko** [comment]
tag 被划掉也很正常啊……没划掉就是清流

另外不依赖资深出五星是很难的，不要觉得保底四星的组合很容易出五星

**Comment by Ryanrrt** [comment]
又看了一下好像公招没有包含清流啊...是还没更新吗（我记得以前用着没问题呀

**Comment by Tsuk1ko** [comment]
#52

**Comment by Ryanrrt** [comment]
从搜索引擎搜到方舟工具箱的网址是www.acy.moe，这个是没有更新数据的网站。lolicon那个地址是没有问题的。辛苦啦！（acy那个是被别人盗用了吗？

**Comment by Tsuk1ko** [comment]
到也不算盗用，本项目是开源的，任何人都可以自行部署
