### ISSUE TITLE
公开招募计算的能力标签排序不按照游戏内同名能力标签顺序

### ISSUE THREAD

**Issue by bearpool** [arkntools/arknights-toolbox#146]
![image](https://user-images.githubusercontent.com/6859847/140651857-a5b5f7e1-efa2-4838-81f4-3cb530114aa9.png)
从2021-11-04的更新后，公开招募计算的能力标签不按照游戏内的同名能力标签顺序来排序了，虽然不是不能用，但毕竟习惯了更新前和游戏内同步的顺序了。

**Comment by Tsuk1ko** [comment]
😢确实，之前为了美观调了一下排序，因为一直用 OCR 所以真没注意到原来这个默认顺序就是游戏里的顺序，那我还是改回来吧

**Comment by bearpool** [comment]
![image](https://user-images.githubusercontent.com/6859847/140731064-e3accd4a-203c-458d-af06-1b6f6a112014.png)
治疗的位置大概不对，治疗肯定在费用回复前
