### ISSUE TITLE
手机版访问公招页面内容缺失

### ISSUE THREAD

**Issue by XCaben** [arkntools/arknights-toolbox#147]
貌似是页面过窄导致内容被隐藏了

**Comment by Tsuk1ko** [comment]
请提供截图

**Comment by XCaben** [comment]
> 请提供截图

F12改成手机版也能看

![Screenshot_20211125-122824.jpg](https://user-images.githubusercontent.com/35393474/143379917-36dcdce5-268b-42d5-a3c3-6eb1ad74fd31.jpg)

**Comment by Tsuk1ko** [comment]
这个……哪里缺失了？

**Comment by XCaben** [comment]
草，眼岔了，还以为那是个图片
