### ISSUE TITLE
精英材料云端备份失败

### ISSUE THREAD

**Issue by ZHUzx0219** [arkntools/arknights-toolbox#149]
我试过挂流量或者vpn，但是都提示备份失败，请问是我这边的网络问题还是什么问题？

**Comment by Tsuk1ko** [comment]
Jsonstorage API 改了，稍后我更新下

**Comment by ZHUzx0219** [comment]
![1](https://user-images.githubusercontent.com/38600121/146676108-6e646703-b4c3-4496-b951-dfab1ff03f84.png)
更新之后仍然备份失败

**Comment by Tsuk1ko** [comment]
旧的同步码已经不能用了，要删掉，重新生成新的

我又发布了一个版本，更新后会统一把同步码清空，更新后再使用

**Comment by ZHUzx0219** [comment]
好的 打扰了，感谢
