### ISSUE TITLE
Bug回報

### ISSUE THREAD

**Issue by daniel12818** [arkntools/arknights-toolbox#150]
網頁版稀有度1的素材消失
手機版雙酮消失

**Comment by Tsuk1ko** [comment]
稀有度1的素材默认不显示，需要在筛选中启用

![image](https://user-images.githubusercontent.com/24877906/147377034-49f9a2c6-cd0e-404a-88f8-ebdd4156db0f.jpeg)

**Comment by daniel12818** [comment]
手機版稀有度1的雙酮依舊沒顯示，其他5個有正常顯示
    在 2021年12月25日 星期六 上午11:57:39 [GMT+8]， ***@***.***> 寫道：  
 
 


稀有度1的素材默认不显示，需要在筛选中启用



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tsuk1ko** [comment]
可以提供截图或者录屏吗

**Comment by Tsuk1ko** [comment]
截图设置部分和材料消失的部分
