### ISSUE TITLE
功能建议：为“重置需求&已有”等三个按钮添加二次确认

### ISSUE THREAD

**Issue by EdiTurn** [arkntools/arknights-toolbox#151]
因为将工具箱切换到后台有时会立刻被系统杀掉，所以在手机上修改数据后，我会手动进行备份。而由于手机上重置按钮和数据同步按钮上下排列，已有两次误触到重置按钮，随后被同步到云端的遭遇。因此希望可以为这三个重置按钮添加二次确认的提示，谢谢。

![Screenshot_2021-12-28-10-26-52-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/5492805/147521857-e2897143-845c-43ac-8887-e483583a91f7.jpg)

**Comment by Tsuk1ko** [comment]
重置之后可以撤销，撤销功能不足以满足你的需求么

**Comment by EdiTurn** [comment]
去试了一下，应该是我发现点错后，习惯性的再去点击数据同步，反而导致撤销的提示消失……
