### ISSUE TITLE
Ceobe二技能8-9无法计算总体力

### ISSUE THREAD

**Issue by Hydrodeuteride** [arkntools/arknights-toolbox#154]
Ceobe二技能8-9无法计算总体力
如题
![image](https://user-images.githubusercontent.com/100023191/154797266-6ef1c4d8-0f12-4689-8f6a-e571c93be281.png)
在勾选ceobe二技能8-9后计算“我该刷什么图”时出现空白

（btw，非常感谢您的工具）

**Comment by Tsuk1ko** [comment]
可以提供一下你当前的输入数据吗？

云端数据同步-离线备份恢复-备份

**Comment by Hydrodeuteride** [comment]
> 

4SMxp4n30qXWesuXCRmae0

**Comment by Tsuk1ko** [comment]
不对吧，只有这么点？

**Comment by Tsuk1ko** [comment]
我这里没能复现

![image](https://user-images.githubusercontent.com/24877906/154828279-ccf5593f-ad29-43c3-9dfc-737099342b3e.png)

**Comment by Tsuk1ko** [comment]
试下进无痕模式然后打开工具箱使用这个同步码恢复，看看是否正常

**Comment by Hydrodeuteride** [comment]
感谢！ 问题解决了。谢谢您~
