### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Endless-dream** [arkntools/arknights-toolbox#156]
精英材料计算中，史尔特尔，精一和技能1→7同时勾选时，需要固源岩数量错误。需要19，显示仍需12。

**Comment by Tsuk1ko** [comment]
你开了稀有度1，源岩是可以合成固源岩的

**Comment by Endless-dream** [comment]
没开啊……我几乎不开稀有度1，而且使用之前有重置需求&已有……但是现在已经好了……复现不出来了……
试了一下，如果开稀有度1并添加源岩的话，它会提示可以合成的数量，例如仍需18(1)。但当时显示的就是需要19，仍需12

**Comment by Tsuk1ko** [comment]
🧐那不清楚了，你确定你没有填写已有7吗

下次遇到的话可以用离线备份，贴一下导出内容

**Comment by Endless-dream** [comment]
确定，下次遇到截图给你看

**Comment by Endless-dream** [comment]
我当时还试了一下，只要把已有调成12，固源岩就会变白

**Comment by Tsuk1ko** [comment]
😢好，下次复现来 reopen
