### ISSUE TITLE
公開招募計算的問題

### ISSUE THREAD

**Issue by C306106** [arkntools/arknights-toolbox#157]
"控場"與其他詞條的保底組合都不會顯示
比如
特種+控場=紅 
先鋒+控場=德克薩斯

**Comment by Tsuk1ko** [comment]
是有的呀
![image](https://user-images.githubusercontent.com/24877906/161393642-d248e2d8-32ca-4c95-8b39-6a8ea8430083.png)
![image](https://user-images.githubusercontent.com/24877906/161393649-bead37d6-c06d-4439-9544-78be86a0f52b.png)

**Comment by C306106** [comment]
![image](https://user-images.githubusercontent.com/102872443/161394324-c1a01b8f-7c5d-4427-b310-8ae5cd725dc8.png)
跟控場有關的都不會被顯示在保底組合

**Comment by C306106** [comment]
![image](https://user-images.githubusercontent.com/102872443/161394415-c2806d78-fa09-4716-9b2d-ebb85c1ac216.png)

**Comment by Tsuk1ko** [comment]
确实

**Comment by C306106** [comment]
感謝您
