### ISSUE TITLE
对已有的备份码云端备份/恢复出错

### ISSUE THREAD

**Issue by Yanstory** [arkntools/arknights-toolbox#158]
控制台显示：400 (Bad Request)
页面上的反馈信息为：备份失败 "PUT operation requires user ID. /v1/json/{userId:Guid}/{itemId:Guid}"
新开备份则无此错误，但之后备份也会出现此错误

顺便手机端无法上下滑动页面

**Comment by Tsuk1ko** [comment]
手机端无法滑动页面？iOS 是正常的，你的手机是什么

**Comment by Tsuk1ko** [comment]
修复了备份问题，滑动问题可以单开一个 issue

**Comment by Yanstory** [comment]
好了一会儿又炸了：
备份失败 "PUT operation requires **non-empty** user ID. /v1/json/{userId:Guid}/{itemId:Guid}"
控制台显示：`PUT https://api.jsonstorage.net/v1/json/00000000-0000-0000-0000-000000000000/<userid> 400`

**Comment by Tsuk1ko** [comment]
嗷，试用用户不给更新，得另找一个服务或者引导用户注册了。。
