### ISSUE TITLE
精英化材料无法备份/恢复

### ISSUE THREAD

**Issue by ZHUzx0219** [arkntools/arknights-toolbox#159]
当同步码为空时可以正常生成同步码，但在已有同步码时会备份失败，出现以下提示
![image](https://user-images.githubusercontent.com/38600121/162584590-5e10d901-47f9-4598-8ebe-905bfa0c927f.png)

**Comment by Tsuk1ko** [comment]
一会再找个免费调用额度大点的 json storage

**Comment by ZHUzx0219** [comment]
好的 辛苦大佬了

**Comment by Tsuk1ko** [comment]
解决了，不用换了，是因为漏写了 header ……
