### ISSUE TITLE
云同步备份失败，exceeded the call limit(10000)

### ISSUE THREAD

**Issue by bearpool** [arkntools/arknights-toolbox#161]
![image](https://user-images.githubusercontent.com/6859847/162837639-645789e9-fb0c-4b60-a930-1266e757aed1.png)

查了一下ExtendsClass的限制
Usage limits:
10000 requests per month
Bin is limited to 100 KB
Quota for an account: 10 MB

所以是每月的请求超过了？

其实大家注册个平台私用api key也没关系嘛……

**Comment by Tsuk1ko** [comment]
看来还是逃不掉……
