### ISSUE TITLE
10章掉落更新后刷图规划数据异常

### ISSUE THREAD

**Issue by iiSlash** [arkntools/arknights-toolbox#163]
![image](https://user-images.githubusercontent.com/45996401/163529641-b656b1b7-1e62-49f0-b2ed-8020889847ef.png)
![V6P U)%NYL4{@WXI1Y%{O7S](https://user-images.githubusercontent.com/45996401/163529671-9cc2d4e9-af89-4451-ab56-2da44a48f57e.png)
![ZGV7OO)W)VCBI 7EW}UO`71](https://user-images.githubusercontent.com/45996401/163529830-84dc69c3-9280-4550-8cd9-ba0ea95135bd.png)

10章掉落更新后规划数据异常，强制更新后越来越离谱了
试了一下取消勾选需求狗粮后正常 重新勾选后复现
同步码c1489bdb2a51

**Comment by Tsuk1ko** [comment]
貌似是 10-2 导致目前的需求狗粮算法炸了，先不勾选需求狗粮吧

**Comment by iiSlash** [comment]
好的，感谢
暂时看10-2掉落一般，我就先直接取消10-2了，是正常的

**Comment by Tsuk1ko** [comment]
目前对需求狗粮增加了一个阈值设置，如果出现理智消耗过高的情况可以尝试减小阈值

简单来说这个阈值是用来控制“我觉得为了多得点狗粮去刷素材效率更低的图是赚的”的程度
