### ISSUE TITLE
關於JP幹員外部連結網站 gamerclub 資料老舊

### ISSUE THREAD

**Issue by mythnc** [arkntools/arknights-toolbox#165]
距離gamerclub上次更新已經是2020年3月，

比較新的幹員雖然依舊可以連到 gamerclub，但是會顯示404

是否有可能改用其他的外部網站？例如 https://arknights.wikiru.jp/

Ref 
https://wiki.gamerclub.jp/anwiki/index.php?title=%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8

**Comment by Tsuk1ko** [comment]
[arknights.wikiru.jp](https://arknights.wikiru.jp/) 的问题在于我不清楚如何对应干员与页面网址

一般是通过名字对应的，但是该 wiki 用了非 utf 编码进行 URL 编码

我一开始猜的是 gbk，发现对于名字仅包含平假或片假的干员是适用的，但含有汉字的就又不对了

有没有大佬指点一下，或者另外提供一个方便对应网址的日文 wiki

**Comment by mythnc** [comment]
我猜應該是 EUC-JP

ref - https://www.benricho.org/moji_conv/16-URLencode_EUC.html

**Comment by Tsuk1ko** [comment]
> 我猜應該是 EUC-JP
> 
> ref - [benricho.org/moji_conv/16-URLencode_EUC.html](https://www.benricho.org/moji_conv/16-URLencode_EUC.html)

看起来确实是的，明天我研究一下
