### ISSUE TITLE
【增加功能】攒抽规划工具/预期抽卡计算

### ISSUE THREAD

**Issue by zhangweijian97** [arkntools/arknights-toolbox#170]
您好，我看了这个视频 [明日方舟：从现在从零开始攒抽能攒够一井吗？月卡党至少258抽，离目标并不远 - 哔哩哔哩](https://www.bilibili.com/read/cv11840747) 之后，觉得是不是能做一个预期抽卡资源计算器？

我参考这篇文章 [2022统计一下去年抽卡资源 小月卡党收支基本持平](https://ngabbs.com/read.php?tid=30132473&_fu=60594250%2C1&rand=447)，尽可能列出获取抽卡资源的方式

- 日/周/月常奖励
	- 日常任务，每天，100 合成玉
	- 周常任务，每周，500 合成玉
	- 每周剿灭，每周，1800 合成玉
	- 每月签到，每月，1 抽
	- 绿票商店，每月，4 抽 加 600 合成玉
	- 黄票商店，（自定义）次数，38 抽
- 限定活动相关，（自定义）次数
	- 前瞻直播，（自定义）合成玉
	- 送 10 连，10 抽
	- 挖矿奖励，11 抽
	- 每日送抽，14 抽
	- 签到活动，约 600 合成玉
	- 商店，3 抽
- 活动相关
	- 故事集，（自定义）次数，商店 3 抽 加（自定义）源石 加（自定义）紫票
	- 支线故事，（自定义）次数，商店 3 抽 加（自定义）源石
	- 支线故事复刻，（自定义）次数，商店 3 抽 加（自定义）源石 加（自定义）紫票
	- 主线，（自定义）次数，（自定义）源石
	- 危机合约，无抽卡资源
	- 签到活动，（自定义）次数，（自定义）源石 加 （自定义）合成玉 加 （自定义）抽
	- 网页活动，（自定义）次数，（自定义）合成玉
- 其它零碎
	- 新剿灭 首通奖励，n（自定义）次，n 乘 1500 合成玉
	- 悖论模拟，（自定义）次数，200 合成玉
	- 邮件补偿，（自定义）次数，（自定义）合成玉
	- 制作组通讯，（自定义）次数，200 合成玉
- 搓玉，每日，300 合成玉
- 组合包
	- 月卡，每天，200 合成玉；加每月 6 源石
	- 大月卡，每月，42 源石 加 10 抽
	- 其它礼包，（自定义）次数，（自定义）源石 加 （自定义）抽
- 源石交易所
	- 6 元，首冲，3 源石
	- 30 元，首冲，12 源石
	- 98 元，首冲，40 源石
	- 198 元，首冲，80 源石
	- 328 元，首冲，132 源石
	- 648 元，首冲，260 源石
	- 6 元，非首冲，1 源石
	- 30 元，非首冲，7 源石
	- 98 元，非首冲，24 源石
	- 198 元，非首冲，50 源石
	- 328 元，非首冲，90 源石
	- 648 元，非首冲，185 源石
- 购买皮肤，（自定义）次数，负（自定义）源石

合成玉 600 = 1 抽
源石 1 颗 = 180 合成玉
情报凭证（紫票）20 = 100 合成玉

注，对于循环周期，应该选择是否包括当期
注，新剿灭约每两个月出一次
注，矿区每日奖励在 300 到 600 不等，14 天，拢共约 6300，记为 11 抽
注，活动的源石数量不定，对于还未发生的活动，只能顾及数量和奖励，应每个单独列出
注，可以选择购买皮肤，从最后总数倒扣源石
注，对于许多自定义次数（比如邮件补偿），可以根据过往记录，给出一个推荐
注，黄票是否要单独出一个计算？
注，氪金礼包应该单独列出
注，最前面输入一下当前资源，包括合成玉，源石，单抽卡。然后上述各项都可以选择/反选。最后还有一个不计源石的选项。然后最终计算得到抽卡数量

最终的页面，使用流程可能是，输入当前资源，输入目标时间，依次勾选自己可以使用的获取抽卡资源的渠道，后面还有一些选项是往回扣抽卡资源，最后计算得到，从今天到你预期的日期，你将会拥有多少抽卡资源。

不知道制作这个计算器的难度大不大呢？

开发者大大你是否有兴趣做？

我是否也可以加入进来？我有一点编程基础，之前给明日计划这个脚本写过基建换班（auto.js），不过网页 vue这些东西完全没有接触过。一点都不知道要怎么做。如果开发者大大有意愿的话，我希望能和您一起开发这个计算器。

**Comment by Tsuk1ko** [comment]
你好，感谢功能建议

看这个描述的话，计算逻辑上不是很复杂，但是体力活很多（UI 层面）

我个人可能没有兴趣去做这个功能，我认为这个属于“可以，但没有必要”类型的功能，感觉实现起来花费的精力相比受益人数和受益程度不是很值得：我觉得会精打细算到如此地步的玩家应该是很少数的，大部分人比起自己勾选填写这么多项去得到一个十分精确的结果，可能更愿意直接参考别人的总结（比如你提到的 NGA 贴）来估算自己大概能攒多少玉

~而且社畜之后整个人都比较怠惰~

如果你想加入进来贡献代码的话我非常欢迎，但完全没接触过前端的话，想自学独自完成这个功能是很耗费时间和精力的，还需要理解我现有的一些组件和设计（阅读屎山），不知你觉得是否值得

如果你真的要做的话，我可以在个人时间允许的情况下提供一些帮助

**Comment by zhangweijian97** [comment]
您好，感谢回复！

我也不确定自己能否坚持😂。不过目前对这个东西确实挺感兴趣，所以想多了解一下，试试看。

我感觉 UI 上，和现有的“公开招募计算”和“干员升级计算”中包含的元素差不多。Tag 的点击、选项的选择和反选、数字的自定义输入。应该够用了。所以我可以直接参考现有的代码。

我是不是应该在自己电脑开发单独一个网页？如何测试？如何保持和现有的网页的一致性？如何合并？要如何学习您的代码？要完成这个需求，最少需要学习什么？

总的来说，我现在想不出一个明确的步骤，来完成这个需求，可否请您给出一些指导建议。比如，第一步，把 xxx 的教程看了。第二步，看库里面的 xxx 文件，yyy 代码。第三步，自己在电脑上开发测试单独网页。第五步，把新网页和现有的网站合并。第六步，上传 github，等待审核。

还有一些细节，比如git的版本控制和分支控制的建议之类的。这俩我都没有用过😂，只简单了解过概念。

**Comment by zhangweijian97** [comment]
噢对了，关于“大部分人比起自己勾选填写这么多项”。我觉得可以设置一些预设的选项，比如“无氪”，“微氪”，等。点击之后，后面那一大堆就自动钩上。然后用户能继续微调

**Comment by zhangweijian97** [comment]
关于方案的更新，我觉得这个其实是最难的地方。应该想办法做成，能用简单的方式更新方案，比如出了新的制作组通讯，有详细的新活动信息，然后只需要添加几行信息，就能更新。这个不知道应该怎么设计。

另外，应该也要有办法，接受用户的建议。比如能有管理员，提交表单，自动更新网页。

继而也要有防止破坏的回滚机制？感觉越来越复杂了😂

**Comment by Tsuk1ko** [comment]
> 关于方案的更新，我觉得这个其实是最难的地方。应该想办法做成，能用简单的方式更新方案，比如出了新的制作组通讯，有详细的新活动信息，然后只需要添加几行信息，就能更新。这个不知道应该怎么设计。
> 
> 另外，应该也要有办法，接受用户的建议。比如能有管理员，提交表单，自动更新网页。
> 
> 继而也要有防止破坏的回滚机制？感觉越来越复杂了😂

不推荐这样做，方案的制订应当使维护成本降到最低，例如这个月是否包含制作组通讯等这类不确定因素都应当由用户自行填写，而不是人工维护

当月的活动图的数量倒是可以通过解包获得，可以先由用户输入，后续我来补充逻辑

如果用户想提建议新增一些项，可以直接通过 issue

**Comment by Tsuk1ko** [comment]
开发环境建议

IDE 使用 VSCode，至少安装 volar, eslint, prettier 插件

浏览器安装 [Vue Devtools](https://devtools.vuejs.org/guide/installation.html) 插件
