### ISSUE TITLE
仓库材料识别能否支持导入 json？

### ISSUE THREAD

**Issue by MistEO** [arkntools/arknights-toolbox#190]
我们是一款本地小助手软件 [MAA](https://github.com/MaaAssistantArknights/MaaAssistantArknights)，前段时间开发出了仓库识别的功能，会自动帮用户滑动仓库+识别

初步计划是我们生成一个仓库材料信息的 json，用户复制 json 文本后可以在网页上直接粘贴并导入，这样用户就不用一张一张截图并上传了 ✿✿ヽ(°▽°)ノ✿

至于具体的 json 格式倒无所谓，怎么方便怎么来，~~反正都要 hardcode~~

**Comment by Tsuk1ko** [comment]
这个好

json 格式我目前的想法就是使用简单的`材料ID:数量`键值对，像这样

https://github.com/arkntools/depot-recognition/blob/main/test/cases/cn_iphone12_0/result.json

材料ID来自于解包，和企鹅物流使用的一致

**Comment by MistEO** [comment]
MAA [v4.4.0-beta.3](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases) supported ✿✿ヽ(°▽°)ノ✿

![image](https://user-images.githubusercontent.com/18511905/188941917-816b0ae5-9560-45ab-b754-e03a4f227e1a.png)


![image](https://user-images.githubusercontent.com/18511905/188941881-e694aab5-aa44-4cdc-965a-24725b17911f.png)

**Comment by Tsuk1ko** [comment]
好耶
