### ISSUE TITLE
材料建议及反馈

### ISSUE THREAD

**Issue by 545426** [arkntools/arknights-toolbox#192]
反馈：电脑端（edge）浏览器不显示“从json导入”如图
![-8c9a5617bd0ca8c](https://user-images.githubusercontent.com/64343218/189551869-9a5843d3-aef9-4f77-a767-dbfa6f7b30ba.png)

原因：windows端明日方舟脚本MAA已支持导入到“明日方舟工具箱”但浏览器没有导入按钮，发送到手机粘贴又会被手机输入法剪贴板限制字数，无法一次性复制所有内容。
建议：增加模组材料、芯片、芯片助剂、技巧概要等材料的识别和计算
感谢阅读，期待您的回复，再见

**Comment by Tsuk1ko** [comment]
电脑端也有的，请检查你的工具箱是不是没有更新

详情见 #52

**Comment by 545426** [comment]
感谢回复，已经搞定了，因为我一直用的是旧版本的网页（明日方舟工具箱 (moeyy.cn)所以才没有，现在已切换到新版（明日方舟工具箱 (lolicon.app)。麻烦问一下材料计算以后计划支持芯片/技能书/模组的导入和计算吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月12日(星期一) 中午12:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [arkntools/arknights-toolbox] 材料建议及反馈 (Issue #192)





 
电脑端也有的，请检查你的工具箱是不是没有更新
 
详情见 #52

**Comment by Tsuk1ko** [comment]
已经在计划内，但因为改动比较大所以咕了很久，具体什么时候能支持我也不好说
![image](https://user-images.githubusercontent.com/24877906/189572943-ad48f2fc-8345-490e-aee8-63692dc79fb3.png)
