### ISSUE TITLE
[Bug]arkn.lolicon.app必须删除cookie才可以访问

### ISSUE THREAD

**Issue by lanhao34** [arkntools/arknights-toolbox#199]
我大概从15个小时前开始无法访问[arkn.lolicon.app](https://arkn.lolicon.app/)，起初以为是网站挂了，后来发现用其他浏览器或者隐身模式都可以访问，检查以后猜测是cookie出问题了，最后我在浏览器中清除cookie就能打开页面。

我个人的问题虽然已经解决，但当时打开页面的时候一直提示的是“此网站已经被永久转移或无法访问”，比较具有迷惑性，希望能检查一下是否是因为版本迭代后cookie不兼容导致页面无法加载。

**Comment by Tsuk1ko** [comment]
但是这是一个纯静态站……

**Comment by lanhao34** [comment]
这。。。那可能是我本地浏览器插件的问题吧。
我当时用F12看了一下网络请求，[arkn.lolicon.app](https://arkn.lolicon.app/)返回的内容是空的，也不知道为啥
总而言之，如果是我个人问题的话，那就close吧
