### ISSUE TITLE
無法識別素材

### ISSUE THREAD

**Issue by Alnas1210** [arkntools/arknights-toolbox#200]
無法正常識別凝膠以後的素材

![Screenshot_20220928-225508](https://user-images.githubusercontent.com/105498421/192814640-4c11cdfe-b758-49a2-85d8-cd546c603a03.png)

![Screenshot_20220928-225715](https://user-images.githubusercontent.com/105498421/192814714-6fe1d67b-2100-4ee1-b5e4-908cab99c2ac.png)

![Screenshot_20220928-225715-2](https://user-images.githubusercontent.com/105498421/192814762-f07480f1-96d3-40f2-90bf-db47fa6bc15f.png)

**Comment by Tsuk1ko** [comment]
有问题，这个仓库材料的排序和正常排序不一样，不知道是什么原因

看了下国服美服日服韩服都是一样的顺序，但目前没有新的台服解包，所以我也无法判断是游戏 bug 还是台服真的改了顺序

**Comment by Alnas1210** [comment]
台服的排序一直是這樣
以前成功讀取的圖檔現在也讀不出來

**Comment by Tsuk1ko** [comment]
确实，仔细看了下历史记录发现是国服的排序在近期改了

**Comment by Tsuk1ko** [comment]
已修复，需注意服务器不能选国服
