### ISSUE TITLE
加入红票统计

### ISSUE THREAD

**Issue by smilecold** [arkntools/arknights-toolbox#203]
![image](https://user-images.githubusercontent.com/20356498/194446418-4150e20a-cafa-410d-a749-b4b8e409dd0f.png)

只需求近卫芯片, 然而特种芯片没有隐藏

此外, 是否可以将红票加入统计呢

**Comment by Tsuk1ko** [comment]
这是因为近卫和特种可以互相转换，你可以在设置里关闭“允许芯片转换”来隐藏

确实可以加，我看看吧
