### ISSUE TITLE
芯片识别错误

### ISSUE THREAD

**Issue by smilecold** [arkntools/arknights-toolbox#204]
![image](https://user-images.githubusercontent.com/20356498/194447022-6dd48766-732e-4706-95fe-1cd28d04fefe.png)

![image](https://user-images.githubusercontent.com/20356498/194447068-43b7fcfe-1aac-47b8-9ddc-f9166a78c86a.png)

近卫芯片 和 术师芯片 没有正确识别

**Comment by Tsuk1ko** [comment]
长的太像了，偶尔会发生这种问题，暂时没有好的办法

截图的时候尽量不要让这种芯片处于中心的位置，不要把后面的信物截进来就行

不需要担心前面的材料被重复导入，导入是覆盖不是追加

![image](https://user-images.githubusercontent.com/24877906/194467713-f04a26c4-10e9-42c7-b555-4f21cde56f21.png)
