### ISSUE TITLE
勾除芯片和概要还是会显示在干员需求

### ISSUE THREAD

**Issue by dl0ne** [arkntools/arknights-toolbox#207]
勾除了芯片和概要，干员需求材料还是会显示，不知是bug还是什么

**Comment by Tsuk1ko** [comment]
筛选中选不选择只会影响是否展示和刷图计算是否计算，待办中依然是显示的

**Comment by dl0ne** [comment]
> 

所以目前待办一定是显示的是吗，因为我觉得没什么必要显示这两个，本身获取途径非常固定，显示了我还得手动再输入我的芯片和概要

**Comment by Tsuk1ko** [comment]
是，不过感觉确实也可以做成会一并控制是否在待办中显示

**Comment by Tsuk1ko** [comment]
另外可以用仓库识别的，倒也不用手动输入

**Comment by dl0ne** [comment]
> 是，不过感觉确实也可以做成会一并控制是否在待办中显示

因为我喜欢多个干员需求一起刷材料，芯片不填会有种材料一直不够升不了的错觉，自动识别也试过，截图也没办法一张搞定还不如我手动键入哈哈
