### ISSUE TITLE
API-key not found请求帮助

### ISSUE THREAD

**Issue by 545426** [arkntools/arknights-toolbox#216]
粘贴key后点击备份，下方提示“bin not found”删除分割线后提示key错误，请问怎么处理？
![-65e02e63872eb6ad](https://user-images.githubusercontent.com/64343218/198857967-711fbb90-b7a7-4e7c-b1c6-ceffcd3009b3.png)

**Comment by Tsuk1ko** [comment]
过久没有忘这个同步码备份就会这样，删除同步码再备份来新建一个即可

**Comment by 545426** [comment]
> 

问题已解决，感谢
