### ISSUE TITLE
完成待办时尝试合成缺少的材料

### ISSUE THREAD

**Issue by konataks** [arkntools/arknights-toolbox#220]
比如某待办需要某材料 8个，目前只有 3 个，但是子材料足够合成 5 个，这时勾选完成会提示材料不足，需要手动去合成每个材料，然后再重新完成待办。

希望可以加个选项 `[ ] 完成待办时尝试自动合成`
或者 弹出提示 `材料不足，是否尝试自动合成`

**Comment by Tsuk1ko** [comment]
设计如此，你在缺材料到加工站合成的时候直接对照工具箱告诉你要合多少个，每合完一种材料就点一下对应的合成就好了，这个本质上也是一种待办，能让你知道哪些材料合够了哪些没合

点击材料不够的代办也会自动帮你标记需要的材料，不怕找不到

**Comment by konataks** [comment]
理解这个设计想法。主要是因为在游戏里已经合过一遍了，想要个偷懒直接扣材料的可选功能。不然要专三一个技能需要手动点合并的次数还蛮多的。
