### ISSUE TITLE
在工具箱中增加艾丽妮专精模拟器的建议

### ISSUE THREAD

**Issue by Shunia3055** [arkntools/arknights-toolbox#221]
如题，艾丽妮是常用专精幻神，若追求极致效率需要多次换人。如果能在工具箱中增加类似b站up@公孙长乐在艾丽妮相关视频下分享的excel的功能，即通过输入辅助教官专精效率而自动计算出换人时间的功能的话，会方便不少_(:зゝ∠)_

**Comment by Shunia3055** [comment]
还可以和ffxiv采集时钟一样增加闹钟提醒换人功能

**Comment by Tsuk1ko** [comment]
> 还可以和ffxiv采集时钟一样增加闹钟提醒换人功能

这个就算了，也不是采集那种间隔比较短的提醒，网页一直挂后台计时器会冻结的，还可能被 chrome 回收，拿手机定计时器或者闹钟靠谱点……
