### ISSUE TITLE
所有頁面均出現 TyperError: Failed to fetch 並且沒法使用

### ISSUE THREAD

**Issue by g79g74** [arkntools/arknights-toolbox#226]
所有頁面均出現 TyperError: Failed to fetch 並且沒法使用

**Comment by Tsuk1ko** [comment]
请提供浏览器及版本信息，以及开发者工具 Console 截图

**Comment by g79g74** [comment]
![屏幕截图 2023-03-22 232657](https://user-images.githubusercontent.com/128462044/226904919-da2e01ae-8982-404a-aadf-b8bbb70f3e55.png)
![屏幕截图 2023-03-22 232847](https://user-images.githubusercontent.com/128462044/226905075-9e77268b-c9aa-440a-8013-e25eb67bc49c.png)
![屏幕截图 2023-03-22 232922](https://user-images.githubusercontent.com/128462044/226905240-3e0752f8-a2c9-4752-af58-7d19346af884.png)
![屏幕截图 2023-03-22 233025](https://user-images.githubusercontent.com/128462044/226905384-69d25937-40df-4029-8009-097f4ad976c8.png)

**Comment by Tsuk1ko** [comment]
看起来是网络问题，不过你这边既然能更新到工具箱本体为什么会连不上数据服务，两个用的是同一个CDN🤔

可以分别 ping 一下  `arkn.lolicon.app` 和 `data.arkntools.app` 看看截图么

**Comment by Tsuk1ko** [comment]
也可以尝试使用 arknbak.lolicon.app

**Comment by Tsuk1ko** [comment]
那这太奇怪了，我 edge 同版本也没能复现这个问题

arkn 和其数据服务都是 Gcore CDN，arknbak 和其数据服务都是 Cloudflare CDN，明明站点能打开，数据服务却连接重置

**Comment by g79g74** [comment]
我剛剛好像找到原因了 好像是大學wifi這邊禁止了(?) 也不知道確實原因 但是用4G就可以用了 感謝你的幫助

**Comment by Tsuk1ko** [comment]
😂好吧
