### ISSUE TITLE
无法将阿米娅加入材料计算

### ISSUE THREAD

**Issue by Zumurrud** [arkntools/arknights-toolbox#228]
![image](https://user-images.githubusercontent.com/100747704/235332808-4ba2e150-b392-4f5a-b533-5307ac6a658d.png)

我可以在预设列表中搜索她，但单击带有她的名字和图标的框不会弹出通常的复选框列表。

Automatic translation from: "I can search for her in the Preset list, but clicking on the box with her name and icon does not pop up the usual list of checkboxes."

**Comment by Tsuk1ko** [comment]
Thank you for reporting this, fixed.
