### ISSUE TITLE
建議將基建技能敘述的繁簡統一

### ISSUE THREAD

**Issue by SHYISONLINE** [arkntools/arknights-toolbox#232]
![image](https://github.com/arkntools/arknights-toolbox/assets/101704478/cb4dfbaf-98af-4423-9147-fbe92d03ccbb)
![image](https://github.com/arkntools/arknights-toolbox/assets/101704478/2988447a-c0a8-4ea3-b022-9c543739c2e5)
如上圖所示，根據查詢時使用的繁簡會得到不完整的結果
我使用的是繁體中文介面/CN服

**Comment by Tsuk1ko** [comment]
因为台服解包没有人维护了，所以目前繁中的数据无法更新，这些新的文案都没有繁中版本

也许我可以试试简繁转换，但效果不一定好

**Comment by Tsuk1ko** [comment]
现在所有游戏文本都会从简中自动转换成繁中，如果发现有偏差可以再开 issue 告知
