### ISSUE TITLE
UI优化：增加大号材料增减按钮

### ISSUE THREAD

**Issue by Shunia3055** [arkntools/arknights-toolbox#237]
建议在专精材料计算器中，在材料名称旁添加大号的库存增减“+”“-”按钮。需求量由专精目标决定，很少手动调整，所以不需要；但已有量容易因为发放奖励、合成副产品等原因频繁产生变化，增加大号按钮更方便操作。现在的实在太小了，即使在pc上也不是很好点。

**Comment by Tsuk1ko** [comment]
🤔那边已经有合成按钮了，再加名字怕是要挤没了

其实输入框激活之后用键盘上下键也能调，虽然是没有直接点方便

**Comment by Shunia3055** [comment]
原来上下键也可以调！现在才知道。感谢！

神代綺凛 ***@***.***> 于 2023年6月27日周二 12:08写道：
