### ISSUE TITLE
移动端排版问题

### ISSUE THREAD

**Issue by corneria1** [arkntools/arknights-toolbox#238]
个人在使用移动端的时候，精英材料计算板块，待办区干员名字显示不完整，单字干员甚至会直接无法看到。
![Screenshot_2023-07-12-01-41-01-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/arkntools/arknights-toolbox/assets/139263613/c5119bc5-be91-4469-b672-f1b7a291fd00)

**Comment by Tsuk1ko** [comment]
无法复现……

![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/08fe8be1-5210-475f-ab92-b5f5a9d339d2)

可以尝试点击左上角菜单，然后疯狂点击菜单上方的“Arknights Toolbox”文字，左下角会出现一个vConsole，打开看看有没有error
