### ISSUE TITLE
小鸟专精时间中表格的描述问题

### ISSUE THREAD

**Issue by Fuynkio** [arkntools/arknights-toolbox#242]
![图片](https://github.com/arkntools/arknights-toolbox/assets/50935992/7075d661-4672-4038-887e-1fd5e12ebfd8)
表格上的专精列 能不能更改一下描述 把：
1 改成 7级→专精1 
2 改成 专精1→专精2
3 改成 专精2→专精3
(本人经常在早上起猛了的时候开始专精，今天早上更是看了10分钟才分清楚谁是谁，不写明白点看不懂的）

"请" 这个字显示不正确我还不清楚是什么情况

还有 我的专精1→专精2 时间好像不对  应该跟[https://github.com/arkntools/arknights-toolbox/issues/241](url) 这个一样问题

**Comment by Tsuk1ko** [comment]
时间不对就说明前面没触发减半👀

**Comment by Neutralization** [comment]
换人时间的计算不对，这个1小时40分应该是指专精显示的剩余时间，即现在开始专精到还剩1小时40分，而不是从当前时间往后1小时40分换人。
专精一和专精二差了整整8小时，却都在1小时40分后换人，专精二艾莉妮站岗时间显然远远超过5小时，这完全没节省到时间。

**Comment by Tsuk1ko** [comment]
1小时40分就是指的在1小时40分后换人，不是剩余时间，是以当前等级开始专精为时间起点，方便你用手机设计时器之类的

例如上面表格表示的是

专0->专1，从11:02开始专精，1小时40分后换人，16:02完成，该阶段总共耗时6小时40分（1小时40分+艾丽妮5小时）

后面同理

没吃减半的场景直接从2开始的场景并未计算，后续会增加设置项 #241

**Comment by Neutralization** [comment]
考虑设计时器的话建议加一下剩余时间的显示，考虑到忘记定时的场合，直接用剩余时间和加成效率可以反过来推算剩余X时间时应该换人。
换人时间=剩余时间-(5/(1+5%)/(1+5%+x%))
这样后半部分值可以完全固化查表，不需要重复计算。
而且剩余时间本质就是为了保证艾莉妮后段专精的5小时，这样也不用考虑前段减半是否生效的问题了。

**Comment by Tsuk1ko** [comment]
有道理，可以加

**Comment by Tsuk1ko** [comment]
加了剩余时间，并修复了加成输入的一些bug
