### ISSUE TITLE
精英材料计算在筛选部分物品后时执行刷图规划在一些情况下会导致卡死

### ISSUE THREAD

**Issue by AdorableParker** [arkntools/arknights-toolbox#249]
![image](https://github.com/arkntools/arknights-toolbox/assets/35246761/59d5bb8c-a3e4-4c8d-9337-b21dad6a0029)

**Comment by Tsuk1ko** [comment]
因为你这里把筛选关到只剩金素材了，刷图规划是会按你的筛选考虑的，没有直接刷取金素材的途径

后面我对这种情况加个提醒吧

**Comment by AdorableParker** [comment]
只剩芯片也卡死（这又是什么原因
