### ISSUE TITLE
精英材料计算没有洋灰数据，预设中输入洋灰无法找到

### ISSUE THREAD

**Issue by crazyjoker667** [arkntools/arknights-toolbox#253]

**Comment by Tsuk1ko** [comment]
请认准 REAMDE 中写明的项目官方网站

![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/58ab1c8b-3c69-41b8-97d7-0e4fe4d35804)

**Comment by crazyjoker667** [comment]
我的问题，洋灰已经在之前预设，后续重复预设，以为出现bug

**Comment by Tsuk1ko** [comment]
az，这么说的话确实有点优化空间，可以改成允许搜索已经添加到预设的角色，点击后打开编辑对话框

**Comment by Tsuk1ko** [comment]
新版本将支持搜索已添加的干员
