### ISSUE TITLE
不可对预设中的干员更改勾选来更新待办事项

### ISSUE THREAD

**Issue by Fuynkio** [arkntools/arknights-toolbox#255]
先
![图片](https://github.com/arkntools/arknights-toolbox/assets/50935992/fe045813-12ea-4556-a72a-785407ed082a)
![图片](https://github.com/arkntools/arknights-toolbox/assets/50935992/a562cf42-a6c7-4312-8a58-f86b0e9c23d2)

后
![图片](https://github.com/arkntools/arknights-toolbox/assets/50935992/2da89888-b6b5-4c96-abb2-f281d0d18104)
![图片](https://github.com/arkntools/arknights-toolbox/assets/50935992/a1e2b20c-2dbd-44e8-ada0-ce0389d27690)

在隐私模式下测试过 还是这样

**Comment by Tsuk1ko** [comment]
已修复，等几分钟更新
