### ISSUE TITLE
Cloud Sync Issue

### ISSUE THREAD

**Issue by HideriKan** [arkntools/arknights-toolbox#265]
In the Material Calculation tab, when I try to use the backup function (either with the backup button or the automatic updalod), I get a "backup failed" error.

I have already tried to delete the sync code and the API key, but I still get the same message. I am not sure if its something to do with my network connection, ExtendsClass or something else. 

I have also grabbed the error message from the console:
```
/#/material:1 Access to XMLHttpRequest at 'https://json.extendsclass.com/bin/<MySyncCode>' from origin 'https://arkn.lolicon.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
ajax.js:10 
        
        
       PUT https://json.extendsclass.com/bin/<MySyncCode> net::ERR_FAILED
ajax @ mdui.js:2203
(anonymous) @ ajax.js:10
d @ ajax.js:9
(anonymous) @ ajax.js:68
d @ regeneratorRuntime.js:45
(anonymous) @ regeneratorRuntime.js:133
(anonymous) @ regeneratorRuntime.js:74
n @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
e @ ajax.js:76
cloudSaveData @ index.js:1322
click @ DataSyncDialog.vue:1
Bn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
Na.i._wrapper @ vue.runtime.esm.js:7500
```
I can access _https://json.extendsclass.com/bin/<MySyncCode>_ myself just fine aswell.
The error is practicly the same with or without SyncCode

Sorry if this has already been submitted, but I have been having this error for a few days now.

**Comment by Tsuk1ko** [comment]
It seems that extendsclass.com don't provide json storage service anymore.

I need to find another free service. 😢

**Comment by Tsuk1ko** [comment]
Well, I searched for a long time but couldn't find an excellent substitute, so I decided to make one myself...
