### ISSUE TITLE
手机云端备份恢复数据失败

### ISSUE THREAD

**Issue by Black1312** [arkntools/arknights-toolbox#269]
小米浏览器在工具箱新地址（http://arkntools.app/#/material）备份失败，恢复失败
![2d446a1b1a662b567beb809e58ec2bda](https://github.com/arkntools/arknights-toolbox/assets/64343218/2c68f3cb-0454-43d1-9f25-edadd84c9ffd)

**Comment by Tsuk1ko** [comment]
看看是否网络原因，挂个代理看看

**Comment by Black1312** [comment]
> 看看是否网络原因，挂个代理看看

手机和电脑处于同一wifi，电脑可以，手机就不行。手机已尝试数据网络和挂代理，都备份和恢复失败

**Comment by MagakiReimu** [comment]
荣耀，夸克浏览器也是，备份失败Failed to fetch，PC端的云同步码给手机是恢复失败Failed to fetch，手机PC同无线WiFi网络，手机端清空缓存，也一样提示Failed to fetch
![微信图片_20240505123641](https://github.com/arkntools/arknights-toolbox/assets/36392404/08e28c24-337a-475b-9066-10b077523a02)

**Comment by Tsuk1ko** [comment]
试试直接在浏览器中打开 https://arknights-toolbox-json-storage.lolicon.app 是什么表现

**Comment by MagakiReimu** [comment]
> 试试直接在浏览器中打开 https://arknights-toolbox-json-storage.lolicon.app 是什么表现
> 
> 我开始怀疑会不会是手机没有信任LE的根证书

显示OK，两个浏览器都是的
![微信图片_20240505140839](https://github.com/arkntools/arknights-toolbox/assets/36392404/a1716daf-96df-4de9-a2ed-d98c057647a6)

**Comment by Tsuk1ko** [comment]
![](https://github.com/arkntools/arknights-toolbox/assets/24877906/4aa2b2cf-3c6f-4d95-901d-550bb0eeb856)

那真不懂为什么了，换用 chrome 呢

**Comment by Tsuk1ko** [comment]
点开侧边栏，点击上方 logo 10次，会启用 vConsole，然后去备份或者恢复一下，点开 vConsole 看看 network 里面对应请求是什么情况

![IMG_8786](https://github.com/arkntools/arknights-toolbox/assets/24877906/45fad4e9-048d-401e-8898-2d8b35752198)

![IMG_8785](https://github.com/arkntools/arknights-toolbox/assets/24877906/8507503d-fd7f-4f1d-8a40-3c21aa4dbfc2)

**Comment by MagakiReimu** [comment]
Status=Pending, 图1图2为需求拉普兰德模组材料空，图3为需求空材料空
![微信图片_20240505143344](https://github.com/arkntools/arknights-toolbox/assets/36392404/6de801a2-72f7-4f6c-b86e-388146a97f06)
![微信图片_20240505143350](https://github.com/arkntools/arknights-toolbox/assets/36392404/f7fc028f-f2e9-4ac1-b231-463f3fd1bf89)
![微信图片_20240505143437](https://github.com/arkntools/arknights-toolbox/assets/36392404/a941605d-72ce-4153-959a-43d9a9de5892)

**Comment by Tsuk1ko** [comment]
那看来这个也不能看出什么，得真机调试直接看 devtools 才行……

**Comment by MagakiReimu** [comment]
> 那看来这个也不能看出什么，得真机调试直接看 devtools 才行……

没玩过真机调试，我找个教程试试

**Comment by Tsuk1ko** [comment]
webview 调试

不一定所有浏览器都能调，可能要在浏览器软件设置里找一下有没有开关

1. 手机打开 usb 调试，连PC
2. PC Chrome 打开 chrome://inspect/#devices 要勾选 Discover USB Device
3. 点击对应页面的 inspect

**Comment by Black1312** [comment]
> 那看来这个也不能看出什么，得真机调试直接看 devtools 才行……

喜报，小米浏览器清除浏览器数据后可以正常恢复了

**Comment by Black1312** [comment]
> 那看来这个也不能看出什么，得真机调试直接看 devtools 才行……

小米浏览器：https://arkntools.app/#/可正常使用，http://arkntools.app/#/获取基础数据失败且页面空白仅显示标题

**Comment by Tsuk1ko** [comment]
![](https://github.com/arkntools/arknights-toolbox/assets/24877906/4aa2b2cf-3c6f-4d95-901d-550bb0eeb856)

啊，原来你们打开的是 http ？

**Comment by MagakiReimu** [comment]
> ![](https://private-user-images.githubusercontent.com/24877906/327993436-4aa2b2cf-3c6f-4d95-901d-550bb0eeb856.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTI4NDQsIm5iZiI6MTcxNDg5MjU0NCwicGF0aCI6Ii8yNDg3NzkwNi8zMjc5OTM0MzYtNGFhMmIyY2YtM2M2Zi00ZDk1LTkwMWQtNTUwYmIwZWViODU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODFiMWUyNjkzYjc5OTI5OTkwMWE1ODM5YzM4ZjUzNTc5NDcyNDdmNmY1MjlmMTdiY2UzYTk4ZDViOTY1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMG1Dknpl7ujvM4FbiIXeJEZM9jn_3zSvQj07Ro3y4o) [ ![327993436-4aa2b2cf-3c6f-4d95-901d-550bb0eeb856.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTI4NDQsIm5iZiI6MTcxNDg5MjU0NCwicGF0aCI6Ii8yNDg3NzkwNi8zMjc5OTM0MzYtNGFhMmIyY2YtM2M2Zi00ZDk1LTkwMWQtNTUwYmIwZWViODU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODFiMWUyNjkzYjc5OTI5OTkwMWE1ODM5YzM4ZjUzNTc5NDcyNDdmNmY1MjlmMTdiY2UzYTk4ZDViOTY1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMG1Dknpl7ujvM4FbiIXeJEZM9jn_3zSvQj07Ro3y4o](https://private-user-images.githubusercontent.com/24877906/327993436-4aa2b2cf-3c6f-4d95-901d-550bb0eeb856.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTI4NDQsIm5iZiI6MTcxNDg5MjU0NCwicGF0aCI6Ii8yNDg3NzkwNi8zMjc5OTM0MzYtNGFhMmIyY2YtM2M2Zi00ZDk1LTkwMWQtNTUwYmIwZWViODU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODFiMWUyNjkzYjc5OTI5OTkwMWE1ODM5YzM4ZjUzNTc5NDcyNDdmNmY1MjlmMTdiY2UzYTk4ZDViOTY1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMG1Dknpl7ujvM4FbiIXeJEZM9jn_3zSvQj07Ro3y4o) ](https://private-user-images.githubusercontent.com/24877906/327993436-4aa2b2cf-3c6f-4d95-901d-550bb0eeb856.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTI4NDQsIm5iZiI6MTcxNDg5MjU0NCwicGF0aCI6Ii8yNDg3NzkwNi8zMjc5OTM0MzYtNGFhMmIyY2YtM2M2Zi00ZDk1LTkwMWQtNTUwYmIwZWViODU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODFiMWUyNjkzYjc5OTI5OTkwMWE1ODM5YzM4ZjUzNTc5NDcyNDdmNmY1MjlmMTdiY2UzYTk4ZDViOTY1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMG1Dknpl7ujvM4FbiIXeJEZM9jn_3zSvQj07Ro3y4o) [ ](https://private-user-images.githubusercontent.com/24877906/327993436-4aa2b2cf-3c6f-4d95-901d-550bb0eeb856.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTI4NDQsIm5iZiI6MTcxNDg5MjU0NCwicGF0aCI6Ii8yNDg3NzkwNi8zMjc5OTM0MzYtNGFhMmIyY2YtM2M2Zi00ZDk1LTkwMWQtNTUwYmIwZWViODU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODFiMWUyNjkzYjc5OTI5OTkwMWE1ODM5YzM4ZjUzNTc5NDcyNDdmNmY1MjlmMTdiY2UzYTk4ZDViOTY1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hMG1Dknpl7ujvM4FbiIXeJEZM9jn_3zSvQj07Ro3y4o)
> 
> 啊，原来你们打开的是 http ？

啊这，居然真是http的
![微信图片_20240505150700](https://github.com/arkntools/arknights-toolbox/assets/36392404/9a336786-eee5-4f2d-8812-40b05c84f46b)
好像是旧域名重定向过来的锅？

**Comment by Tsuk1ko** [comment]
重定向的时候我是写死了 https 的，不知为何你们打开了 http 的

https://github.com/arkntools/arknights-toolbox/blob/1a867db357dd93068db2aaad771f9bd0c7c054f2/src/utils/migration.js#L43-L47

不过没事，我刚刚去改了 CDN 的 http 重定向，我确实忘记给新域名开启 http 重定向到 https 了，应该过一段时间就完全生效了

`.app` 域名其实是进了 HSTS Preload List 的，目前国际上的主流浏览器都会默认强制跳转到 https，但国产浏览器不一定会使用该列表，所以没有跳转

![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/bdead97d-d4dd-4607-9d07-b11276083b09)
