### ISSUE TITLE
无法从森空岛导入数据

### ISSUE THREAD

**Issue by hpc1** [arkntools/arknights-toolbox#272]
![image](https://github.com/arkntools/arknights-toolbox/assets/45529629/62b8f739-9033-49c8-a04f-74843ae3adae)
从森空岛网页获取cred后，使用导入功能显示未查询到绑定角色信息

**Comment by Tsuk1ko** [comment]
是B服吗

**Comment by hpc1** [comment]
是官服，森空岛app中是可以查看到角色绑定的

**Comment by Tsuk1ko** [comment]
F12 打开 DevTools 之后再点导入，看看 Network 里 binding 这个请求的 Preview

![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/ef3f7b61-44c6-46c1-9f87-d5528ac754b7)

**Comment by hpc1** [comment]
![image](https://github.com/arkntools/arknights-toolbox/assets/45529629/283a8b2e-5682-46de-87fc-f9fd84739c9b)
wo我看并没有受到请求

**Comment by Tsuk1ko** [comment]
1. 先到材料页面
2. F12
3. 点导入
4. 看 Network，筛选 ![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/8dba40b6-fab7-4bd7-8d9d-a14d69f705c2)

**Comment by hpc1** [comment]
啊，理解错了，还以为森空岛里读取
![image](https://github.com/arkntools/arknights-toolbox/assets/45529629/aab3c3d4-a1e0-45ed-8d7d-1171a0861818)

**Comment by hpc1** [comment]
![image](https://github.com/arkntools/arknights-toolbox/assets/45529629/851704b4-b908-4f32-ad05-032f938a3483)

**Comment by Tsuk1ko** [comment]
貌似是因为没有在森空岛里设置默认游戏角色，修复了，等一会网站更新

**Comment by hpc1** [comment]
更新之后可以使用了，我看了一下确实没有设置默认角色，感谢大佬
