### ISSUE TITLE
基建技能干员头像会被鼠标拖走

### ISSUE THREAD

**Issue by fuyn101** [arkntools/arknights-toolbox#274]
没有使用 no-pe 是刻意的嘛
https://github.com/arkntools/arknights-toolbox/blob/fbe440ba66be12cf58fb128690d1df27f264b44c/src/components/riic/SkillTr.vue#L12

https://github.com/arkntools/arknights-toolbox/blob/fbe440ba66be12cf58fb128690d1df27f264b44c/src/components/riic/SkillTr.vue#L28
![recording](https://github.com/arkntools/arknights-toolbox/assets/151902446/39deb237-7094-4c6e-8c37-bb58665fb52f)

**Comment by Tsuk1ko** [comment]
应该只是忘了（
