### ISSUE TITLE
Web端无法使用键盘快捷键

### ISSUE THREAD

**Issue by Artoria2e5** [arkntools/arknights-toolbox#275]
macOS 13.6.7 (22G720)
Safari 17.5 (18618.2.12.111.5, 18618)

- `⌘Z`、`⌘⇧T` 等浏览器快捷键无法使用
- 浏览器插件Vimari的快捷键需要先点击一下网页才能激活使用

**Comment by Tsuk1ko** [comment]
macOS 14.4.1 Safari 17.4.1 没复现
