### ISSUE TITLE
精英材料计算从森空岛导入数据提示failed to fetch

### ISSUE THREAD

**Issue by ChaiDWind** [arkntools/arknights-toolbox#281]
官服，从maa导入是正常的，从森空岛用Token导入就成功了一次，清除数据之后再导入就一直提示failed to fetch，Cred可以正常导入
![Snipaste_2024-09-26_07-10-29](https://github.com/user-attachments/assets/a078f0d1-5b77-43ae-a0a9-c3173e79dbd3)

**Comment by Tsuk1ko** [comment]
目前 yj 对 API 的风控貌似变严了，先用 cred 吧，后面我看看有没有办法

![image](https://github.com/user-attachments/assets/87553577-74ed-49ec-842a-ebffadf7c554)

**Comment by Tsuk1ko** [comment]
可以试试看能用了不
