### ISSUE TITLE
支持从森空岛导入作战记录和龙门币

### ISSUE THREAD

**Issue by duststarocean** [arkntools/arknights-toolbox#285]
仓库不识别作战记录，导致我每次用个干员升级计算，都得重新输入有多少作战记录，很麻烦，希望修改

**Comment by Tsuk1ko** [comment]
不考虑增加作战记录识别，我目前没什么好办法处理中文单位，也没有动力寻找解决方法

但可以增加从森空岛导入作战记录、龙门币数据的能力，以后直接用森空岛导入功能

现在有森空岛导入之后基本也不需要手动截图识别了

**Comment by duststarocean** [comment]
问题回复如此快，大赞，等以后我试试森空岛导入，看能不能解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [arkntools/arknights-toolbox] 关于仓库识别和干员升级计算的优化请求 (Issue #285)




 
不考虑增加作战记录识别，我目前没什么好办法处理中文单位，也没有动力寻找解决方法
 
但可以增加从森空岛导入作战记录、龙门币数据的能力，以后直接用森空岛导入功能
 
现在有森空岛导入之后基本也不需要手动截图识别了

**Comment by duststarocean** [comment]
感谢改进！佬！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月7日(周六) 下午2:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [arkntools/arknights-toolbox] 支持从森空岛导入作战记录和龙门币 (Issue #285)




 
Closed #285 as completed via e917fad.
