### ISSUE TITLE
友情链接位置申请

### ISSUE THREAD

**Issue by SHUAXINDIARY** [arkntools/arknights-toolbox#286]
哈喽，这边有做一个明日方舟生涯生成器的站点，不知道可以不可以申请一个友情链接位置
---
[仓库地址](https://github.com/SHUAXINDIARY/Arknights)
[访问地址](https://arknights.shuaxinjs.cn/)
--
页面效果如下：
![Arknights (2)](https://github.com/user-attachments/assets/f1f4bd55-46a9-4c8c-b64a-73dc644004ff)

**Comment by Tsuk1ko** [comment]
友链系统是小刻食堂提供的，你可以咨询小刻食堂的“洛梧藤”，但对项目有一定要求
