### ISSUE TITLE
请问能增加根据仓库截图识别已有素材的功能吗

### ISSUE THREAD

**Issue by syoulo** [arkntools/arknights-toolbox#44]
每次刷完图之后素材数量都会变动，如果能根据仓库的素材截图自动更新已有素材数据就好了。。小白不懂技术上难度。如果dalao觉得实现起来有意义而且不是太困难就太好了😢

**Comment by Tsuk1ko** [comment]
@syoulo 如果你能找到开源的实现，当然可以加

这涉及到机器学习，我并不具有这方面的专长于兴趣，并且要训练也需要大量样本，我自己肯定是懒得做的

**Comment by syoulo** [comment]
原来如此。看来还是很困难的啊。我以为那个截图识别干员词条的难度跟这个差不多。。谢谢回复！

**Comment by Tsuk1ko** [comment]
@syoulo 识别词条是纯粹的文字识别，有很多现成的服务，而识别仓库需要识别图像，是需要自己训练的

**Comment by syoulo** [comment]
话说这些素材图案都是确定的，训练的样本也需要很多吗？是不是各种分辨率的手机上面都截一张图当成样本库就够了。？我今天去了解了一下pytorch不知道我能不能靠自学训练一个network出来。要是成功了能让我加入这个项目吗😳

**Comment by Tsuk1ko** [comment]
可能需要几十张甚至上百张，而且提升识别准确率也要靠大量样本，还得手动标记，所以工作量挺大的🤔

如果能搞出来的话当然非常欢迎将这个功能加到工具箱里

**Comment by lynnguo666** [comment]
这个功能是有的，可以看这个开源的仓库https://github.com/GachaSalt/ArkToolDemo/tree/master/img
页面是https://gachasalt.github.io/ArkToolDemo/#/image

**Comment by Tsuk1ko** [comment]
@lynnguo666 这个仓库只是一个 dist，即可部署的网站成品，代码是经过压缩打包的，没有源码的话就无法移植过来

也就是说该工具箱实际上没有开源

**Comment by lynnguo666** [comment]
那试着把这个网站成品修改一部分然后进行移植呢

**Comment by Tsuk1ko** [comment]
@lynnguo666 做不到，而且由于没有 map，连想找到这部分功能的代码在哪里都做不到

**Comment by lynnguo666** [comment]
那可以使用类似于[{"name":"炽合金块","need":0,"have":2},{"name":"炽合金","need":0,"have":15}]这种格式导入吗

**Comment by Tsuk1ko** [comment]
@lynnguo666 目前没有，可以考虑做一个自定义导入

**Comment by lynnguo666** [comment]
这个也是可以，然后通过其他平台的识别数据进行导入（曲线救国吧），我一会看看能不能找到代码区

**Comment by Tsuk1ko** [comment]
已实装
