### ISSUE TITLE
希望增加“只刷优质关卡”的功能。

### ISSUE THREAD

**Issue by YoungBoron** [arkntools/arknights-toolbox#45]
比如要刷研磨石与异铁组时，软件规划关卡为5-7，但5-7只是掉率较高，而理智利用率低。如果要理智利用率高，应该刷4-8和S4-1。
关上的“优劣程度”可以在[https://aog.wiki/](https://aog.wiki/)网站上获得，里面红色的关卡是较优的。

**Comment by Tsuk1ko** [comment]
可，其实我这里也有算优劣，就是关卡性价比，不过和 aog 的最优在部分素材上略有出入，到时候看看他们的算法有没有能借鉴优化的

**Comment by Elypha** [comment]
不知道是否考虑先做一个"根据企鹅物流样本数最小值"来过滤关卡的功能
比如我计算材料时发现

> ![image](https://user-images.githubusercontent.com/30290883/183533823-ab693375-cd3c-4557-8272-8bc10ca6ab77.png)

而在企鹅物流上这个关卡只有一个记录

> ![image](https://user-images.githubusercontent.com/30290883/183533920-a75b4457-0fa5-4ba6-900b-867629ee323c.png)

虽然很难说哪些是优质关卡，不过似乎可以先排除这些样本过少的关卡可能带来的误差？（带一下 @Tsuk1ko

**Comment by ZhaoZuohong** [comment]
可否参考[明日方舟一图流])https://yituliu.site/)的数据？理智效率表示“掉落物理智价值期望之和”，也就是表示一关是否为“优质关卡”。例如 5-7 理智效率只有 90% 左右，而 10-12 作为研磨石的定价关，理智效率为 100%。

相关数据可以通过 API 获取：

- 蓝材料最优图：<https://backend.yituliu.site/stage/t3?expCoefficient=0.625>；[响应数据字段说明](https://yituliu.site/docs/#_7)
- 绿材料最优图：<https://backend.yituliu.site/stage/t2?expCoefficient=0.625>；[响应数据字段说明](https://yituliu.site/docs/#_9)

更为灵活的方式是通过[物品价值](https://yituliu.site/value)计算关卡的效率。例如将 5-7 的各项掉落物的掉率与理智价值相乘、再求和：

$$
1.0617 \times 6.891 + 0.3448 \times 31.202 + 252 \times 0.0036 \approx 18.9818
$$

这一关花费 21 理智，理智效率只有 $18.9818 \div 21 \approx 0.9039 = 90.39\\%$。

所有物品的理智可通过 <https://backend.yituliu.site/item/value?expCoefficient=0.625> 获得（[返回字段说明](https://yituliu.site/docs/#_15)）。

如有兴趣，欢迎加一图流的开发群（QQ）938710832 前来一叙。

**Comment by Tsuk1ko** [comment]
> 可否参考[明日方舟一图流](https://yituliu.site/)的数据？理智效率表示“掉落物理智价值期望之和”，也就是表示一关是否为“优质关卡”。例如 5-7 理智效率只有 90% 左右，而 10-12 作为研磨石的定价关，理智效率为 100%。
> 
> 相关数据可以通过 API 获取：
> 
> * 蓝材料最优图：[backend.yituliu.site/stage/t3?expCoefficient=0.625](https://backend.yituliu.site/stage/t3?expCoefficient=0.625)；[响应数据字段说明](https://yituliu.site/docs/#_7)
> * 绿材料最优图：[backend.yituliu.site/stage/t2?expCoefficient=0.625](https://backend.yituliu.site/stage/t2?expCoefficient=0.625)；[响应数据字段说明](https://yituliu.site/docs/#_9)
> 
> 更为灵活的方式是通过[物品价值](https://yituliu.site/value)计算关卡的效率。例如将 5-7 的各项掉落物的掉率与理智价值相乘、再求和：
> 
> 1.0617×6.891+0.3448×31.202+252×0.0036≈18.9818
> 
> 这一关花费 21 理智，理智效率只有 18.9818÷21≈0.9039=90.39%。
> 
> 所有物品的理智可通过 [backend.yituliu.site/item/value?expCoefficient=0.625](https://backend.yituliu.site/item/value?expCoefficient=0.625) 获得（[返回字段说明](https://yituliu.site/docs/#_15)）。
> 
> 如有兴趣，欢迎加一图流的开发群（QQ）938710832 前来一叙。

感谢建议！原来一图流有后端接口，我一直都不知道😂

**Comment by Tsuk1ko** [comment]
现在可以在刷图设置里面设置最小理智效率

也支持在刷图规划时直接动态修改设置查看结果

![chrome_L0aJU7W808](https://github.com/arkntools/arknights-toolbox/assets/24877906/81fe37be-ea82-428f-9e93-b53d9dfe156b)
