### ISSUE TITLE
可以在精英材料中显示技巧概要、芯片和芯片助剂的库存吗？

### ISSUE THREAD

**Issue by bearpool** [arkntools/arknights-toolbox#46]
现在利用精英材料功能来规划精英化和升级技能时，仍然需要通过干员的精英化或者技能升级页面来判断还需要多少技巧概要、芯片或芯片助剂，希望在精英材料功能中能对这些资源一并规划了

**Comment by Tsuk1ko** [comment]
会考虑

**Comment by z04450445** [comment]
請問現階段依然不考慮追加 技巧概要、芯片等材料嗎

**Comment by Tsuk1ko** [comment]
> 請問現階段依然不考慮追加 技巧概要、芯片等材料嗎

改动较大，优先级不高，暂没有计划加入这些，可能等仓库识别支持技巧概要和芯片后会考虑加入

技巧概要和芯片这类材料的消耗是固定的，完全可以自行管理，要升的时候看看缺多少直接刷即可，我认为做进计算器的意义不大

**Comment by bearpool** [comment]
> > 請問現階段依然不考慮追加 技巧概要、芯片等材料嗎
> 
> 改动较大，优先级不高，暂没有计划加入这些，可能等仓库识别支持技巧概要和芯片后会考虑加入
> 
> 技巧概要和芯片这类材料的消耗是固定的，完全可以自行管理，要升的时候看看缺多少直接刷即可，我认为做进计算器的意义不大

现在最大的困扰就是准备精英化和专精技能时才发现技巧概要或者芯片没准备好，自行管理是可以，但是规划起来（比如有精英材料计算中已经有多个干员在排队了）还是需要另外做计算和记录，这时就很渴望这个功能了。

**Comment by keywet06** [comment]
希望可以在配置预设时候直接改为从多少级升到多少级，这样干员升级计算就不用同步了

或者可以加一些选项：当前材料计算是否计入 芯片/芯片助剂/技巧概要/作战记录/龙门币

**Comment by Tsuk1ko** [comment]
> 希望可以在配置预设时候直接改为从多少级升到多少级，这样干员升级计算就不用同步了

这两个功能我设的比较独立，不太好做联动，会很麻烦，暂时不会考虑

> 或者可以加一些选项：当前材料计算是否计入 芯片/芯片助剂/技巧概要/作战记录/龙门币

支持芯片、技巧概要、模组材料之后是一定会计入的，但是会提供总的筛选开关（在目前的星级筛选那里增加），可以控制计算刷图时是否考虑

--------

画饼：没有意外的话国庆期间可以实装
