### ISSUE TITLE
企鹅物流数据统计API升级

### ISSUE THREAD

**Issue by AlvISsReimu** [arkntools/arknights-toolbox#47]
站长您好：
企鹅物流数据统计的API更新了一下版本，在统计区间上进行了改进。API的使用说明可以参考[这里](https://developer.penguin-stats.io/docs/api-v2-instruction/matrix-api)。
参数方面取消了`show_item_details`和`show_stage_details`，如果您需要这些详细内容的话可以考虑我们的Stage及Item API（[API文档](https://penguin-stats.io/PenguinStats/swagger/swagger-ui.html)），不过这两个主要是我们内部使用，对外参考意义可能不如解包的数据。

谢谢。

**Comment by Tsuk1ko** [comment]
好的，谢谢您特地来告知！
