### ISSUE TITLE
【功能请求/Feature Request】“精英材料计算”模组中，修改升级技能下拉项目后自动勾选技能父选项

### ISSUE THREAD

**Issue by Mark9804** [arkntools/arknights-toolbox#49]
例：如图例所示，当用户将“7→10”修改为“8→10”时，自动勾选左边的“链锯延伸模块”
![Snipaste_2020-05-25_12-56-41](https://user-images.githubusercontent.com/9006264/82779669-60cc5980-9e87-11ea-9694-8ddb9aa0d1f3.png)

**Comment by Tsuk1ko** [comment]
感谢建议，已实装
