### ISSUE TITLE
能否添加合成材料以后自动扣除对应的低等级材料功能？

### ISSUE THREAD

**Issue by Ericli0708** [arkntools/arknights-toolbox#50]
例如有五个固源岩，我在基建合成了一个固源岩组，然后在“精英材料计算”界面添加固源岩组时自动扣除对应数量的固源岩。可以在每个可合成的材料框中添加一个按钮，在满足该材料的合成条件后自动亮起，按下后该材料+1，然后自动扣除对应的低等级材料。这样在大量合成材料以后就不用再费力的统计该扣除多少材料了。

**Comment by Tsuk1ko** [comment]
材料合成功能不是早就有了的么

**Comment by Ericli0708** [comment]
哦这个是怎么用？用了好久都没发现...

**Comment by Ericli0708** [comment]
哦抱歉，没仔细阅读过说明

**Comment by Ericli0708** [comment]
不过能否把这个功能做得明显一些呢？能够看界面就懂怎么用不需要阅读说明。

**Comment by Tsuk1ko** [comment]
我寻思合成两个大字都写在按钮上了甚至都没必要特殊说明把……

**Comment by Ericli0708** [comment]
哦，我的意思是需要点开材料的图片才能发现是合成的界面，不点开的话在外面看不出来合成是在这里。

**Comment by Tsuk1ko** [comment]
不用点进去，这个按钮就是

![image](https://user-images.githubusercontent.com/24877906/82856013-83ba4480-9f3f-11ea-8447-67919e2a9d3a.png)

**Comment by Ericli0708** [comment]
那这个应该是我的问题了，不过多谢告知。我的屏幕是21:9的，工具箱是开在旁边比较小的区域，因为标准模式下一行只能容纳两个材料不方便查看，所以一直使用简洁模式。在这个模式下用了几个月一直都没发现这个合成的功能。

**Comment by Tsuk1ko** [comment]
😂简洁模式主要是方便输入材料用的，简洁模式下材料排序是和仓库一致的比较好对

而合成的时候是由下往上合成，所以在按稀有度分类的普通模式下会比较好找材料

**Comment by Ericli0708** [comment]
哈哈哈，我的锅，去年用灰猫那个工具箱习惯没改过来。
