### ISSUE TITLE
【公告】如果你觉得工具箱数据过旧请进来看

### ISSUE THREAD

**Issue by Tsuk1ko** [arkntools/arknights-toolbox#52]
近期不知道为什么突然有很多人提这类 issue，在提之前请确认：

1. 确保你使用的是 [arkn.lolicon.app](https://arkn.lolicon.app) 或 [arkn-gh.lolicon.app](https://arkn-gh.lolicon.app)，其余站点均为他人部署的，他们可能不会及时与本项目的更新保持同步。  
我在这里也建议各位部署者：如果你没有能力自动或手动保持与本项目的同步，就不要公开给他人使用了，这是对使用者的不负责。
2. 由于 PWA 的更新机制，你可能需要保持页面打开一段时间才能检测到更新并下载，这一过程在页面底部有明显的提示。如果你确认你的工具箱数据是旧的但是一直没有提示更新，请尝试清除浏览器缓存。
3. 如何确认你所使用的工具箱版本是否最新：页面最底处有一个不起眼的版本号，代表了该版本的构建时间（UTC+0），与本项目的 Actions 页面中的运行时间比对即可。

**Comment by miku1958** [comment]
显示数据更新是1/9
<img width="381" alt="image" src="https://github.com/arkntools/arknights-toolbox/assets/24806909/1dc46d3e-992c-4443-8f58-a53266a93c4f">

但是很多新的内容都没有, 比如临光的模组2
<img width="527" alt="image" src="https://github.com/arkntools/arknights-toolbox/assets/24806909/a07a2d44-971a-4646-8c0c-47352f63ee6d">
<img width="990" alt="image" src="https://github.com/arkntools/arknights-toolbox/assets/24806909/53b7b3a1-96d6-4545-8832-4973dd1a93a8">

**Comment by Tsuk1ko** [comment]
@miku1958 看看你右上角的服务器选的是国服吗

![image](https://github.com/arkntools/arknights-toolbox/assets/24877906/001a2807-5072-497c-8450-4d84f07b50b3)

**Comment by miku1958** [comment]
哦是US, 正常了谢谢!
