### ISSUE TITLE
English Arknights Operators

### ISSUE THREAD

**Issue by zhurai** [arkntools/arknights-toolbox#53]
Sorry, I don't know Chinese, so I'll be writing this issue in English.

EN (and JP/KR) Arknights got Code of Brawl (喧闹法) Sidestory now.

- 梅 -> May
- 槐琥 -> Waai Fu
- 莫斯提马 -> Mostima
- 拜松 -> Bison

are now available on those servers

**Comment by Tsuk1ko** [comment]
It seems some thing wrong with automatic update workflow, I will update it now.

Thanks you for reporting.

**Comment by Tsuk1ko** [comment]
It should be updated.
