### ISSUE TITLE
希望增加计算合成时扣除掉正在需求的素材的功能

### ISSUE THREAD

**Issue by yd278** [arkntools/arknights-toolbox#54]
例如，需求2个固源岩组和5个固源岩，已有10个固源岩的情况下，只显示可合成1个固源岩组而非2个。
可以用一个开关来开启/关闭这个功能

**Comment by Tsuk1ko** [comment]
这个功能在什么场景下会用到呢

如果是想优先凑齐某个阶段的材料的话，可以从待办里面得知素材，自行控制合成个数

我后续也会优化下，在待办里面计算材料的可合成个数

**Comment by yd278** [comment]
> 
> 
> 这个功能在什么场景下会用到呢
> 
> 如果是想优先凑齐某个阶段的材料的话，可以从待办里面得知素材，自行控制合成个数
> 
> 我后续也会优化下，在待办里面计算材料的可合成个数

用到的情景是：
用户会根据精英材料计算页面的「可合成」当作合成建议来指导材料合成。但有的时候照着上面的合成了高级材料却发现低级材料不够用了，就又要回去刷低级材料，（而刷低级材料往往是效率很低的）。

**Comment by Tsuk1ko** [comment]
明白了，后续会加这个功能

**Comment by Tsuk1ko** [comment]
已实装
