### ISSUE TITLE
增加“去除部分关卡功能”

### ISSUE THREAD

**Issue by lynnguo666** [arkntools/arknights-toolbox#55]
希望增加“去除部分关卡功能”，选择不计算的关卡，可以在“精英材料计算”页面中“我该刷什么图”内单独设置去除关卡
同时也希望增加仓库识别（类似于这个 https://gachasalt.github.io/ArkToolDemo/#/image ），识别后可以自动导入到材料表中

**Comment by lynnguo666** [comment]
补一个仓库识别的仓库链接https://github.com/GachaSalt/ArkToolDemo/tree/master/img

**Comment by Tsuk1ko** [comment]
刷图规划去除部分关卡的功能已实装
