### ISSUE TITLE
加入“地图”功能

### ISSUE THREAD

**Issue by lynnguo666** [arkntools/arknights-toolbox#57]
就是可以网站模拟放置干员之类的（我在想桃子），找到了个开源的存储库https://github.com/odex21/SomeMapTest，看看能不能实现吧（）

**Comment by Tsuk1ko** [comment]
@lynnguo666 不考虑，这个功能不属于工具箱的主要功能，并且我见过有个网站有关卡战斗干员部署等完整的模拟功能

**Comment by lynnguo666** [comment]
好的，谢谢
