### ISSUE TITLE
【仓库素材导入】希望能增加修改材料功能

### ISSUE THREAD

**Issue by qiutongxue** [arkntools/arknights-toolbox#70]
经常会碰到材料识别出错的情况（有时候换个位置就正常了），这样的话如果能在修改材料数量的基础上增加修改材料的功能应该体验会更好一些。

![识别正确](https://gitee.com/qiutongxue/blog-images/raw/master/img/20200818190147.png)
![识别错误](https://gitee.com/qiutongxue/blog-images/raw/master/img/20200818190124.png)

**Comment by Tsuk1ko** [comment]
修改材料功能是在计划中的，最近太累了我先咕一会😂

因为识别使用了类似二分查找的算法来加快识别速度所以会出现图二的情况，后续会优化的

以及，每次是识别结果导入是覆盖而不是叠加，所以即使多次截图中有重复部分也不影响，截图时尽量不要截到掉落材料外的素材，特别是芯片

**Comment by Tsuk1ko** [comment]
目前算法已经改造完成，考虑到识别错误情况实际非常少，因此不需要修改功能了

如果有识别问题可在反馈收集 issue 内进行反馈
