### ISSUE TITLE
材料图标在 firefox 上的样式异常

### ISSUE THREAD

**Issue by Ericli0708** [arkntools/arknights-toolbox#71]
精英材料计算页面的各种材料图标在更新以后变小了，即使我把网页放大至160%仍然觉得太小，倒不是说看不清，而是图标太小看得比较费力。

![图片](https://user-images.githubusercontent.com/33204722/90524455-a9eb2b80-e1a0-11ea-846d-882d0c82aae6.png)

**Comment by Ericli0708** [comment]
如果能把图标以及字体改回原先的大小就更好了

**Comment by Ericli0708** [comment]
还发现了另外一个问题，规划里面的图标变扁了，完全看不清。

![图片](https://user-images.githubusercontent.com/33204722/90524860-25e57380-e1a1-11ea-98fa-efd974204eb2.png)

**Comment by Ericli0708** [comment]
使用的浏览器是firefox 79.0

**Comment by Tsuk1ko** [comment]
感谢发现问题，已修复
