### ISSUE TITLE
仓库素材识别反馈收集

### ISSUE THREAD

**Issue by Tsuk1ko** [arkntools/arknights-toolbox#72]
## 现状

开发状态：`2021-02-17` 已进入 rc 阶段

识别范围：仅识别**掉落素材**，即不包含狗粮、芯片、信物等

- 目前已经支持任意形态的截图，不再对完整性做要求（但也别太极端……
- 由于使用了二分法来加速识别，处于截图中心的素材尽量不要在识别范围以外，否则可能影响识别速度和准确性

## 反馈

如果出现严重的识别问题，可在该 issue 内进行反馈，特别是材料识别错误

反馈时请带上「**屏幕截图原图**」及「**识别结果界面截图**（包括 debug）」

如果有识别算法方面的建议也可以在此提出

**Comment by InoryLwc** [comment]
![image](https://user-images.githubusercontent.com/44205960/90633015-df9f1b80-e257-11ea-8588-484ae831ea9a.png)

双极纳米片多次识别不出

**Comment by Tsuk1ko** [comment]
@InoryLwc 可以提供下原图么

**Comment by Tsuk1ko** [comment]
算法改造完啦🎉

现在开始重新接受反馈
