### ISSUE TITLE
台服-宿舍基建技能，错误回报

### ISSUE THREAD

**Issue by SeSeTW** [arkntools/arknights-toolbox#74]
您好，我是台服的使用者，小弟發现台服的宿舍基建技能有几个错误
-夜莺：精二技能"提灯女神"的加成效果是0.2
-推进之王：精二技能"狮心王"的加成效果是0.2
-凛冬：精二技能的名称是"冬将军"，加成效果是0.2

辛苦了~这个网页真的很好用，谢谢辛苦的各位(跪

**Comment by Tsuk1ko** [comment]
感谢报告，已经修复
