### ISSUE TITLE
ios手機端無法開啟

### ISSUE THREAD

**Issue by nightMORALS** [arkntools/arknights-toolbox#78]
加入到主畫面的app打不開，用safari或chrome也沒辦法進入工具，只會顯示「無法打開網頁，因為有太多重新導向的動作」，但換用PC端就一點問題都沒有。

**Comment by Tsuk1ko** [comment]
感谢报告问题，现在应该恢复了

**Comment by nightMORALS** [comment]
我試了一下，手機還是不能使用耶....

**Comment by Tsuk1ko** [comment]
尝试清空下浏览器缓存？

**Comment by Tsuk1ko** [comment]
或者多刷新几次，貌似有些 CDN 节点缓存了重定向，我稍后去处理下

**Comment by nightMORALS** [comment]
> 或者多刷新几次，貌似有些 CDN 节点缓存了重定向，我稍后去处理下

將緩存清楚後就可以了，感謝
