### ISSUE TITLE
功能添加建议

### ISSUE THREAD

**Issue by ziluxike** [arkntools/arknights-toolbox#79]
建议添加干员精二 专精材料自动添加到精英材料计算中去 
（抱歉 主要是太懒了 还要看一下PRTS 再回来看一下

**Comment by Tsuk1ko** [comment]
没懂

**Comment by ziluxike** [comment]
不 比如我要专三小羊的火山技能 需要6个D32钢 5个酮阵列 他能在(干员升级计算或直接添加到精英材料计算)中显示
因为我觉得既然推出了仓库素材导入这类懒人福音 想说是否有必要出个这个配合起来就是懒人神器 orz

**Comment by Tsuk1ko** [comment]
已经有了啊，就是预设功能，在精英材料计算里面

**Comment by ziluxike** [comment]
我居然没发现 抱歉....

神代綺凜 <notifications@github.com> 于2020年9月2日周三 下午9:07写道：
