### ISSUE TITLE
右下動圖

### ISSUE THREAD

**Issue by GuiBo0** [arkntools/arknights-toolbox#80]
希望在深色模式下也能看到跟淺色模式右下角一樣的動圖,謝謝:)

**Comment by Tsuk1ko** [comment]
因那张动图是白色背景的，所以无法用在深色模式下

如果有人可以帮忙抠个透明背景的就可以

**Comment by GuiBo0** [comment]
好的,謝謝您

**Comment by GuiBo0** [comment]
我剛剛做好了
![amiya](https://user-images.githubusercontent.com/71174033/94775758-0a51c780-03f3-11eb-8cf4-6b4fb8be9add.gif)

**Comment by GuiBo0** [comment]
這個可以嗎?

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/94777201-a4b30a80-03f5-11eb-82f0-324fef5ff6f6.png)

有白色锯齿就不可以，我就是一直找不到有什么好的方法做出好的效果所以干脆就不放了😂

**Comment by GuiBo0** [comment]
我在試試看好了~

**Comment by GuiBo0** [comment]
這個呢?
![amiya](https://user-images.githubusercontent.com/71174033/94793848-b0123000-040d-11eb-9bbb-ceaf0199681a.gif)

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/94793919-c61ff080-040d-11eb-8252-dc8b2a8d0544.png)

辛苦你了，可惜还是有的，你用浏览器打开，是黑色背景就能看到

**Comment by GuiBo0** [comment]
這個呢?
![amiya](https://user-images.githubusercontent.com/71174033/94798619-71cc3f00-0414-11eb-96b4-2591c896d23d.gif)

**Comment by Tsuk1ko** [comment]
![](https://user-images.githubusercontent.com/24877906/94801657-f0c37680-0418-11eb-8eca-82c73943f0da.jpg)

很可以！能把背景色调成`#121212`吗

第三帧右下角有一点没处理到

![](https://user-images.githubusercontent.com/24877906/94801830-341de500-0419-11eb-87b2-abe025bc82f5.png)

另外其实不用特地进行水平翻转，我直接用 css 控制翻转的

原图都在这里，还有一张柠檬彩蛋如果方便的话希望也能处理，感谢

https://github.com/arkntools/arknights-toolbox/tree/master/src/assets/img

**Comment by GuiBo0** [comment]
![amiya](https://user-images.githubusercontent.com/71174033/94805982-d4770800-041f-11eb-939e-bca8e8035b90.gif)

**Comment by Tsuk1ko** [comment]
![](https://user-images.githubusercontent.com/24877906/94801657-f0c37680-0418-11eb-8eca-82c73943f0da.jpg)

![image](https://user-images.githubusercontent.com/24877906/94806570-c2499980-0420-11eb-8b4a-a4355ce07666.png)

**Comment by GuiBo0** [comment]
![amiya-nm](https://user-images.githubusercontent.com/71174033/94810249-5bc77a00-0426-11eb-92d0-f7349cd9f3a4.gif)

**Comment by GuiBo0** [comment]
吃蘿蔔那張我再重改一下喔

**Comment by Tsuk1ko** [comment]
好

**Comment by Tsuk1ko** [comment]
柠檬的那张背景没有改成`#121212`

**Comment by GuiBo0** [comment]
![amiya-nm](https://user-images.githubusercontent.com/71174033/94811964-aa761380-0428-11eb-916d-b7050f640bfb.gif)

**Comment by GuiBo0** [comment]
![amiya](https://user-images.githubusercontent.com/71174033/94812377-3851fe80-0429-11eb-869c-e4ce24be2f57.gif)

**Comment by Tsuk1ko** [comment]
感谢，马上更新

**Comment by GuiBo0** [comment]
可以在圖片下註明GuiBo嗎~

**Comment by Tsuk1ko** [comment]
当然会的

**Comment by GuiBo0** [comment]
謝謝你:)

**Comment by Tsuk1ko** [comment]
会把你列到贡献者名单中

**Comment by GuiBo0** [comment]
以後有圖要修也可以找我喔

**Comment by Tsuk1ko** [comment]
已发布
