### ISSUE TITLE
希望基建技能筛选能加入自动计算

### ISSUE THREAD

**Issue by miku1958** [arkntools/arknights-toolbox#81]
如果导入已有干员后, 能自动算已有干员最大收益, 比如孑/巫恋/雪雉这类利用其他人的算起来是真的麻烦, 如果能提供比较快速的反选干员自动重新计算就更好了, 这样在干员失智的时候也能比较方便的使用

**Comment by Tsuk1ko** [comment]
没有计算的必要，我既然都提供了排序了，哪些干员收益最高已经很明显了，其他特殊的自己稍微算算就知道，孑和巫恋这类是铁划不来的直接不用上班，除非真的没人可以用了，雪雉这类计算条件简单的实际加多少自己肯定很清楚吧

你要是没头绪我都可以教你，基建 234 的情况下，有些技能要求干员精英等级，没有就当没有吧

- 贸易站x2，3组轮班
  - 企鹅物流三人组  100%
  - 交际三人组      90%  超长待机
  - 雪雉+两个30%的  95%  用来轮班顶替
- 制造站x4，钱和狗粮各两个，8组轮班
  - 专门加作战记录的有6个，刚好2组，提供 190% (30*4+35*2)
  - 专门加贵金属的3个，1组，提供 95% (30*2+35)
  - 清流+槐琥+梅尔，提供 110%
  - 红云+小刻/龟龟/黑角/火神/稀音（选两个，最好是小刻+稀音），提供 76%+，比 3*25 强，备选or轮班用
  - 剩下的通用 25% 的和急性子慢性子和仓库整备那种都用来轮班，

**Comment by miku1958** [comment]
好吧算起来好像的确没什么用, 那的确不需要了
