### ISSUE TITLE
无法勾选待办？

### ISSUE THREAD

**Issue by Killuahiei** [arkntools/arknights-toolbox#82]
在完成部分工作想要勾选待办工作并核算材料时，无法勾选对应条目。操作时会出现灰色光带，但是不会显示任何勾选成功的标志，材料也不会扣除。
谢谢。

**Comment by Tsuk1ko** [comment]
请给出你当前的输入情况，在云端数据同步中的离线备份里导出

**Comment by Killuahiei** [comment]
eyJpbnB1dHMiOnsiMzAwMTEiOlswLDExMF0sIjMwMDEyIjpbMCwxNzFdLCIzMDAxMyI6WzgsNF0sIjMwMDE0IjpbMTQsOF0sIjMwMDIxIjpbMCwxMTVdLCIzMDAyMiI6WzAsNjFdLCIzMDAyMyI6WzQsMzNdLCIzMDAyNCI6WzEzLDI0XSwiMzAwMzEiOlswLDQzOV0sIjMwMDMyIjpbMCwzM10sIjMwMDM0IjpbMjQsMF0sIjMwMDQxIjpbMCwyN10sIjMwMDQyIjpbMCw0MV0sIjMwMDQzIjpbMCw0XSwiMzAwNDQiOlszNCwwXSwiMzAwNTEiOlswLDc2XSwiMzAwNTIiOlswLDU4XSwiMzAwNTMiOlsxMywwXSwiMzAwNTQiOls0Niw0XSwiMzAwNjEiOlswLDEzN10sIjMwMDYyIjpbMCw0OV0sIjMwMDYzIjpbMCw4XSwiMzAwNjQiOls5LDFdLCIzMDA3MyI6WzAsNDVdLCIzMDA3NCI6WzMyLDZdLCIzMDA4MyI6WzUsMV0sIjMwMDg0IjpbNSwwXSwiMzAwOTMiOlswLDY3XSwiMzAwOTQiOlsyNCwwXSwiMzAxMDMiOlsxMCwzNl0sIjMwMTA0IjpbMTAsMF0sIjMwMTE1IjpbMzQsMl0sIjMwMTI1IjpbMzQsMF0sIjMwMTM1IjpbMTIsMF0sIjMxMDEzIjpbNCw2MF0sIjMxMDE0IjpbMTEsOV0sIjMxMDIzIjpbMCwzMV0sIjMxMDI0IjpbMTIsMF19LCJwcmVzZXRzIjpbeyJuYW1lIjoiMjAyX2RlbWtuaSIsInRleHQiOiLloZ7pm7flqIUiLCJ0aUNsYXNzZXMiOlsidGktdmFsaWQiXSwic2V0dGluZyI6eyJldm9sdmUiOltmYWxzZSxmYWxzZV0sInNraWxscyI6eyJub3JtYWwiOltmYWxzZSwxLDddLCJlbGl0ZSI6W1tmYWxzZSw3LDEwXSxbdHJ1ZSw4LDEwXSxbdHJ1ZSw5LDEwXV19LCJzdGF0ZSI6ImVkaXQifX0seyJuYW1lIjoiMTQ3X3NoaW5pbmciLCJ0ZXh0Ijoi6Zeq54G1IiwidGlDbGFzc2VzIjpbInRpLXZhbGlkIl0sInNldHRpbmciOnsiZXZvbHZlIjpbZmFsc2UsZmFsc2VdLCJza2lsbHMiOnsibm9ybWFsIjpbZmFsc2UsMSw3XSwiZWxpdGUiOltbZmFsc2UsNywxMF0sW2ZhbHNlLDcsMTBdLFt0cnVlLDksMTBdXX0sInN0YXRlIjoiZWRpdCJ9fSx7Im5hbWUiOiIxMTNfY3FidyIsInRleHQiOiJXIiwidGlDbGFzc2VzIjpbInRpLXZhbGlkIl0sInNldHRpbmciOnsiZXZvbHZlIjpbZmFsc2UsZmFsc2VdLCJza2lsbHMiOnsibm9ybWFsIjpbZmFsc2UsMSw3XSwiZWxpdGUiOltbZmFsc2UsNywxMF0sW3RydWUsOCwxMF0sW2ZhbHNlLDcsMTBdXX0sInN0YXRlIjoiZWRpdCJ9fSx7Im5hbWUiOiIxMzZfaHNndW1hIiwidGV4dCI6IuaYn+eGiiIsInRpQ2xhc3NlcyI6WyJ0aS12YWxpZCJdLCJzZXR0aW5nIjp7ImV2b2x2ZSI6W2ZhbHNlLGZhbHNlXSwic2tpbGxzIjp7Im5vcm1hbCI6W2ZhbHNlLDEsN10sImVsaXRlIjpbW2ZhbHNlLDcsMTBdLFtmYWxzZSw3LDEwXSxbdHJ1ZSw3LDEwXV19LCJzdGF0ZSI6ImVkaXQifX0seyJuYW1lIjoiMTc5X2NnYmlyZCIsInRleHQiOiLlpJzojroiLCJ0aUNsYXNzZXMiOlsidGktdmFsaWQiXSwic2V0dGluZyI6eyJldm9sdmUiOltmYWxzZSxmYWxzZV0sInNraWxscyI6eyJub3JtYWwiOltmYWxzZSwxLDddLCJlbGl0ZSI6W1tmYWxzZSw3LDEwXSxbZmFsc2UsNywxMF0sW3RydWUsOCwxMF1dfSwic3RhdGUiOiJlZGl0In19LHsibmFtZSI6IjE4OF9oZWxhZ2UiLCJ0ZXh0Ijoi6LWr5ouJ5qC8IiwidGlDbGFzc2VzIjpbInRpLXZhbGlkIl0sInNldHRpbmciOnsiZXZvbHZlIjpbZmFsc2UsZmFsc2VdLCJza2lsbHMiOnsibm9ybWFsIjpbZmFsc2UsMSw3XSwiZWxpdGUiOltbdHJ1ZSw3LDEwXSxbZmFsc2UsNywxMF0sW2ZhbHNlLDcsMTBdXX0sInN0YXRlIjoiZWRpdCJ9fSx7Im5hbWUiOiIyMTNfbW9zdG1hIiwidGV4dCI6IuiOq+aWr+aPkOmprCIsInRpQ2xhc3NlcyI6WyJ0aS12YWxpZCJdLCJzZXR0aW5nIjp7ImV2b2x2ZSI6W2ZhbHNlLGZhbHNlXSwic2tpbGxzIjp7Im5vcm1hbCI6W2ZhbHNlLDEsN10sImVsaXRlIjpbW2ZhbHNlLDcsMTBdLFt0cnVlLDcsMTBdLFt0cnVlLDcsMTBdXX0sInN0YXRlIjoiZWRpdCJ9fSx7Im5hbWUiOiI0MDBfd2VlZHkiLCJ0ZXh0Ijoi5rip6JKCIiwidGlDbGFzc2VzIjpbInRpLXZhbGlkIl0sInNldHRpbmciOnsiZXZvbHZlIjpbZmFsc2UsZmFsc2VdLCJza2lsbHMiOnsibm9ybWFsIjpbZmFsc2UsMSw3XSwiZWxpdGUiOltbZmFsc2UsNywxMF0sW2ZhbHNlLDcsMTBdLFt0cnVlLDcsMTBdXX0sInN0YXRlIjoiZWRpdCJ9fSx7Im5hbWUiOiIzNThfbGlzYSIsInRleHQiOiLpk4PlhbAiLCJ0aUNsYXNzZXMiOlsidGktdmFsaWQiXSwic2V0dGluZyI6eyJldm9sdmUiOltmYWxzZSxmYWxzZV0sInNraWxscyI6eyJub3JtYWwiOltmYWxzZSwxLDddLCJlbGl0ZSI6W1tmYWxzZSw3LDEwXSxbdHJ1ZSw3LDEwXSxbdHJ1ZSw3LDEwXV19LCJzdGF0ZSI6ImVkaXQifX0seyJuYW1lIjoiMTI4X3Bsb3NpcyIsInRleHQiOiLnmb3pnaLpuK4iLCJ0aUNsYXNzZXMiOlsidGktdmFsaWQiXSwic2V0dGluZyI6eyJldm9sdmUiOltmYWxzZSxmYWxzZV0sInNraWxscyI6eyJub3JtYWwiOltmYWxzZSwxLDddLCJlbGl0ZSI6W1tmYWxzZSw3LDEwXSxbdHJ1ZSw3LDEwXSxbZmFsc2UsNywxMF1dfSwic3RhdGUiOiJlZGl0In19LHsibmFtZSI6IjE0MF93aGl0ZXciLCJ0ZXh0Ijoi5ouJ5pmu5YWw5b63IiwidGlDbGFzc2VzIjpbInRpLXZhbGlkIl0sInNldHRpbmciOnsiZXZvbHZlIjpbZmFsc2UsZmFsc2VdLCJza2lsbHMiOnsibm9ybWFsIjpbZmFsc2UsMSw3XSwiZWxpdGUiOltbZmFsc2UsNywxMF0sW3RydWUsOCwxMF0sW2ZhbHNlLDcsMTBdXX0sInN0YXRlIjoiZWRpdCJ9fV19

**Comment by Tsuk1ko** [comment]
你要完成的是哪个角色的哪条待办？

**Comment by Killuahiei** [comment]
本来要完成是推王的待办，因为无法操作且只有一条待办，所以昨天直接删除了推王。
今天想进行星熊的，想起来昨天的问题就尝试了一下，发现还是无法勾选，但是目前并没有要完成的待办内容。

**Comment by Tsuk1ko** [comment]
那请等你能复现 bug 的情况下，给出导出数据并说明是哪条待办无法操作

**Comment by Killuahiei** [comment]
那么请问我要如何操作？比如我现在就可以复现。。。但是因为无法勾选所以我猜并没有办法出现在备份数据中。。。

**Comment by Killuahiei** [comment]
目前尝试不能勾选的：塞雷亚2、3技能，推王2技能，闪灵3技能，W2技能，星熊3技能，夜莺3技能，莫斯提马3技能，温蒂3技能，铃兰3技能，白面鸮2技能，拉普兰德2技能
目前尝试可以勾选的：赫拉格1技能，铃兰2技能
其它干员因为不是我的待办所以没有添加待办

**Comment by Tsuk1ko** [comment]
你的材料不足当然无法完成待办呀……不是写了材料不足四个大字

这个待办是会自动将消耗的材料扣除的，当你材料足够的时候才能完成

**Comment by Killuahiei** [comment]
但是我的W、星熊、莫斯提马、铃兰、白面鸮以及拉普兰德都是显示的需要合成？我没找到合成需要点选的地方？

**Comment by Killuahiei** [comment]
或者说，需要在非简洁模式完成合成，才能算作材料足够可以勾选？

**Comment by Tsuk1ko** [comment]
是的，简洁模式下点击材料图标进入详情页面也可以操作合成

**Comment by Killuahiei** [comment]
明白了，试了一下操作，在简洁模式中找不到合成公式，所以还是非简洁模式较为好用，可以倒推需要合成的材料。我熟悉一下这个操作，谢谢。
