### ISSUE TITLE
Firefox 下白屏

### ISSUE THREAD

**Issue by pingplug** [arkntools/arknights-toolbox#83]
最近更新数据后，网页打开就是白屏，清空网站数据后可以正常访问，关掉标签页再次打开仍旧是白屏。

**Comment by Tsuk1ko** [comment]
Firefox 82 没有复现

console 有没有输出什么错误

**Comment by pingplug** [comment]
bug诡异的消失了

**Comment by pingplug** [comment]
> Firefox 82 没有复现
> 
> console 有没有输出什么错误

确认了，被duckduckgo插件屏蔽了

**Comment by Tsuk1ko** [comment]
> > Firefox 82 没有复现
> > console 有没有输出什么错误
> 
> 确认了，被duckduckgo插件屏蔽了

这……按理来说只有 google analyze 会被屏蔽，怎么直接屏蔽整个页面的

**Comment by pingplug** [comment]
> > > Firefox 82 没有复现
> > > console 有没有输出什么错误
> > 
> > 
> > 确认了，被duckduckgo插件屏蔽了
> 
> 这……按理来说只有 google analyze 会被屏蔽，怎么直接屏蔽整个页面的

https://cdn.jsdelivr.net也被屏蔽了，非常诡异
