### ISSUE TITLE
iPad iOS 14.2 PWA 经常出现无法调用输入键盘的情况

### ISSUE THREAD

**Issue by SquareFan2** [arkntools/arknights-toolbox#89]
点击任何输入框都无法弹出输入键盘，其他应用界面均正常，多次重启PWA无效
请问是系统本身问题吗

**Comment by Tsuk1ko** [comment]
不清楚，我目前还没遇到过这种情况

**Comment by SquareFan2** [comment]
好的，只能先凑合从外部粘贴了😓

**Comment by SquareFan2** [comment]
初步发现在使用侧拉后很容易出现这种情况，将PWA作为侧拉应用使用，返回主界面后再次以侧拉或普通方式打开时经常出现键盘无法调用的错误，其他应用未发现类似的情况

**Comment by Tsuk1ko** [comment]
侧拉指的是什么操作，横向拉动操作杆切换应用？

**Comment by SquareFan2** [comment]
![IMG_0351](https://user-images.githubusercontent.com/75085675/100734636-ef0f3280-340a-11eb-83c2-3bc22028a9b7.PNG)
图中这样的用法

**Comment by Tsuk1ko** [comment]
这应该是 iPadOS 的 bug 了，等修复吧……

**Comment by SquareFan2** [comment]
好的，看来只能等系统更新了
