### ISSUE TITLE
高亮增强：为高亮的素材添加高亮的合成计数

### ISSUE THREAD

**Issue by Yanstory** [arkntools/arknights-toolbox#90]
举例，我现有三个干员的计划A、B、C，它们总共需要15个酮阵列，这个在计数器上是能够显示的
但我想优先完成A计划，所以我点击了该计划高亮了素材，但我无法直接知道需要合成的酮阵列数量，尤其是该计划并不是直接需要酮阵列的
示意图如下可供参考
![image](https://user-images.githubusercontent.com/5153875/101136039-aabca600-3647-11eb-81a7-ddb5350a31b7.png)
（更正：图例需求为6个）

**Comment by Tsuk1ko** [comment]
谢谢，很好的提议，周末安排👌
