### ISSUE TITLE
【精英材料计算】关卡7-5消耗体力错误

### ISSUE THREAD

**Issue by ShitFool** [arkntools/arknights-toolbox#92]
工具里显示消耗体力17，实际应为18。
![A74603FF-D276-4BD1-947E-7C99BE7DE39E](https://user-images.githubusercontent.com/37926841/102008417-2b2b8700-3d6b-11eb-8e23-9849b8bced2c.png)

**Comment by Tsuk1ko** [comment]
17 是次数

17*18=306
