### ISSUE TITLE
Apple M1 上运行明日方舟的库存截图无法识别

### ISSUE THREAD

**Issue by ITJesse** [arkntools/arknights-toolbox#97]
会卡在 Processing images 的地方

![image](https://user-images.githubusercontent.com/3601376/107360475-53d8be80-6b19-11eb-8c2b-e477964e48d8.png)

![image](https://user-images.githubusercontent.com/3601376/107360535-6eab3300-6b19-11eb-9049-b010d369ca7a.png)

**Comment by Tsuk1ko** [comment]
目前暂时不支持识别平板的四行素材截图，只能识别手机的三行素材截图，不过只会识别不出来而不会卡住

卡住应该是有其他问题，可能是 WASM 不能在 M1 芯片上工作，你可以看看 console 有没有什么报错

**Comment by ITJesse** [comment]
console 没有任何报错

**Comment by Tsuk1ko** [comment]
界面卡住的问题已经修复，支持任意行素材截图识别将在新年期间实装，还请稍作等待
