### ISSUE TITLE
备份功能不保存关卡黑名单相关信息

### ISSUE THREAD

**Issue by ZeroRin** [arkntools/arknights-toolbox#98]
这部分信息好像没法通过备份在不同设备间进行同步

另外，黑名单的功能在需要排除大量关卡的时候使用上不太方便，是否有可能实现和arkplanner中类似的选择交互，或者支持那边导出的json信息导入

**Comment by Tsuk1ko** [comment]
可，那么具体改动如下

- [ ] 导入导出将包含所有设置
- [ ] 刷图黑名单改为选择交互形式
